// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spot.proto

package types // import "github.com/33cn/plugin/plugin/dapp/zkspot/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/33cn/plugin/plugin/dapp/zksync/types"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SpotAction struct {
	// Types that are valid to be assigned to Value:
	//	*SpotAction_LimitOrder
	//	*SpotAction_MarketOrder
	//	*SpotAction_RevokeOrder
	//	*SpotAction_ExchangeBind
	//	*SpotAction_EntrustOrder
	//	*SpotAction_EntrustRevokeOrder
	Value                isSpotAction_Value `protobuf_oneof:"value"`
	Ty                   int32              `protobuf:"varint,6,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SpotAction) Reset()         { *m = SpotAction{} }
func (m *SpotAction) String() string { return proto.CompactTextString(m) }
func (*SpotAction) ProtoMessage()    {}
func (*SpotAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{0}
}
func (m *SpotAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotAction.Unmarshal(m, b)
}
func (m *SpotAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotAction.Marshal(b, m, deterministic)
}
func (dst *SpotAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotAction.Merge(dst, src)
}
func (m *SpotAction) XXX_Size() int {
	return xxx_messageInfo_SpotAction.Size(m)
}
func (m *SpotAction) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotAction.DiscardUnknown(m)
}

var xxx_messageInfo_SpotAction proto.InternalMessageInfo

type isSpotAction_Value interface {
	isSpotAction_Value()
}

type SpotAction_LimitOrder struct {
	LimitOrder *SpotLimitOrder `protobuf:"bytes,1,opt,name=limitOrder,proto3,oneof"`
}

type SpotAction_MarketOrder struct {
	MarketOrder *SpotMarketOrder `protobuf:"bytes,2,opt,name=marketOrder,proto3,oneof"`
}

type SpotAction_RevokeOrder struct {
	RevokeOrder *SpotRevokeOrder `protobuf:"bytes,3,opt,name=revokeOrder,proto3,oneof"`
}

type SpotAction_ExchangeBind struct {
	ExchangeBind *SpotExchangeBind `protobuf:"bytes,4,opt,name=exchangeBind,proto3,oneof"`
}

type SpotAction_EntrustOrder struct {
	EntrustOrder *SpotEntrustOrder `protobuf:"bytes,5,opt,name=entrustOrder,proto3,oneof"`
}

type SpotAction_EntrustRevokeOrder struct {
	EntrustRevokeOrder *SpotEntrustRevokeOrder `protobuf:"bytes,7,opt,name=entrustRevokeOrder,proto3,oneof"`
}

func (*SpotAction_LimitOrder) isSpotAction_Value() {}

func (*SpotAction_MarketOrder) isSpotAction_Value() {}

func (*SpotAction_RevokeOrder) isSpotAction_Value() {}

func (*SpotAction_ExchangeBind) isSpotAction_Value() {}

func (*SpotAction_EntrustOrder) isSpotAction_Value() {}

func (*SpotAction_EntrustRevokeOrder) isSpotAction_Value() {}

func (m *SpotAction) GetValue() isSpotAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SpotAction) GetLimitOrder() *SpotLimitOrder {
	if x, ok := m.GetValue().(*SpotAction_LimitOrder); ok {
		return x.LimitOrder
	}
	return nil
}

func (m *SpotAction) GetMarketOrder() *SpotMarketOrder {
	if x, ok := m.GetValue().(*SpotAction_MarketOrder); ok {
		return x.MarketOrder
	}
	return nil
}

func (m *SpotAction) GetRevokeOrder() *SpotRevokeOrder {
	if x, ok := m.GetValue().(*SpotAction_RevokeOrder); ok {
		return x.RevokeOrder
	}
	return nil
}

func (m *SpotAction) GetExchangeBind() *SpotExchangeBind {
	if x, ok := m.GetValue().(*SpotAction_ExchangeBind); ok {
		return x.ExchangeBind
	}
	return nil
}

func (m *SpotAction) GetEntrustOrder() *SpotEntrustOrder {
	if x, ok := m.GetValue().(*SpotAction_EntrustOrder); ok {
		return x.EntrustOrder
	}
	return nil
}

func (m *SpotAction) GetEntrustRevokeOrder() *SpotEntrustRevokeOrder {
	if x, ok := m.GetValue().(*SpotAction_EntrustRevokeOrder); ok {
		return x.EntrustRevokeOrder
	}
	return nil
}

func (m *SpotAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SpotAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SpotAction_OneofMarshaler, _SpotAction_OneofUnmarshaler, _SpotAction_OneofSizer, []interface{}{
		(*SpotAction_LimitOrder)(nil),
		(*SpotAction_MarketOrder)(nil),
		(*SpotAction_RevokeOrder)(nil),
		(*SpotAction_ExchangeBind)(nil),
		(*SpotAction_EntrustOrder)(nil),
		(*SpotAction_EntrustRevokeOrder)(nil),
	}
}

func _SpotAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SpotAction)
	// value
	switch x := m.Value.(type) {
	case *SpotAction_LimitOrder:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LimitOrder); err != nil {
			return err
		}
	case *SpotAction_MarketOrder:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MarketOrder); err != nil {
			return err
		}
	case *SpotAction_RevokeOrder:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RevokeOrder); err != nil {
			return err
		}
	case *SpotAction_ExchangeBind:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExchangeBind); err != nil {
			return err
		}
	case *SpotAction_EntrustOrder:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EntrustOrder); err != nil {
			return err
		}
	case *SpotAction_EntrustRevokeOrder:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EntrustRevokeOrder); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SpotAction.Value has unexpected type %T", x)
	}
	return nil
}

func _SpotAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SpotAction)
	switch tag {
	case 1: // value.limitOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SpotLimitOrder)
		err := b.DecodeMessage(msg)
		m.Value = &SpotAction_LimitOrder{msg}
		return true, err
	case 2: // value.marketOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SpotMarketOrder)
		err := b.DecodeMessage(msg)
		m.Value = &SpotAction_MarketOrder{msg}
		return true, err
	case 3: // value.revokeOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SpotRevokeOrder)
		err := b.DecodeMessage(msg)
		m.Value = &SpotAction_RevokeOrder{msg}
		return true, err
	case 4: // value.exchangeBind
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SpotExchangeBind)
		err := b.DecodeMessage(msg)
		m.Value = &SpotAction_ExchangeBind{msg}
		return true, err
	case 5: // value.entrustOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SpotEntrustOrder)
		err := b.DecodeMessage(msg)
		m.Value = &SpotAction_EntrustOrder{msg}
		return true, err
	case 7: // value.entrustRevokeOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SpotEntrustRevokeOrder)
		err := b.DecodeMessage(msg)
		m.Value = &SpotAction_EntrustRevokeOrder{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SpotAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SpotAction)
	// value
	switch x := m.Value.(type) {
	case *SpotAction_LimitOrder:
		s := proto.Size(x.LimitOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SpotAction_MarketOrder:
		s := proto.Size(x.MarketOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SpotAction_RevokeOrder:
		s := proto.Size(x.RevokeOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SpotAction_ExchangeBind:
		s := proto.Size(x.ExchangeBind)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SpotAction_EntrustOrder:
		s := proto.Size(x.EntrustOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SpotAction_EntrustRevokeOrder:
		s := proto.Size(x.EntrustRevokeOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ZkOrder struct {
	AccountID            uint64             `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	EthAddress           string             `protobuf:"bytes,2,opt,name=ethAddress,proto3" json:"ethAddress,omitempty"`
	Nonce                uint64             `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TokenSell            uint32             `protobuf:"varint,4,opt,name=tokenSell,proto3" json:"tokenSell,omitempty"`
	TokenBuy             uint32             `protobuf:"varint,5,opt,name=tokenBuy,proto3" json:"tokenBuy,omitempty"`
	Amount               uint64             `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Ratio1               uint32             `protobuf:"varint,7,opt,name=ratio1,proto3" json:"ratio1,omitempty"`
	Ratio2               uint32             `protobuf:"varint,8,opt,name=ratio2,proto3" json:"ratio2,omitempty"`
	ValidFrom            uint64             `protobuf:"varint,9,opt,name=validFrom,proto3" json:"validFrom,omitempty"`
	ValidUntil           uint64             `protobuf:"varint,10,opt,name=validUntil,proto3" json:"validUntil,omitempty"`
	Signature            *types.ZkSignature `protobuf:"bytes,20,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ZkOrder) Reset()         { *m = ZkOrder{} }
func (m *ZkOrder) String() string { return proto.CompactTextString(m) }
func (*ZkOrder) ProtoMessage()    {}
func (*ZkOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{1}
}
func (m *ZkOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZkOrder.Unmarshal(m, b)
}
func (m *ZkOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZkOrder.Marshal(b, m, deterministic)
}
func (dst *ZkOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZkOrder.Merge(dst, src)
}
func (m *ZkOrder) XXX_Size() int {
	return xxx_messageInfo_ZkOrder.Size(m)
}
func (m *ZkOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ZkOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ZkOrder proto.InternalMessageInfo

func (m *ZkOrder) GetAccountID() uint64 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *ZkOrder) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *ZkOrder) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ZkOrder) GetTokenSell() uint32 {
	if m != nil {
		return m.TokenSell
	}
	return 0
}

func (m *ZkOrder) GetTokenBuy() uint32 {
	if m != nil {
		return m.TokenBuy
	}
	return 0
}

func (m *ZkOrder) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ZkOrder) GetRatio1() uint32 {
	if m != nil {
		return m.Ratio1
	}
	return 0
}

func (m *ZkOrder) GetRatio2() uint32 {
	if m != nil {
		return m.Ratio2
	}
	return 0
}

func (m *ZkOrder) GetValidFrom() uint64 {
	if m != nil {
		return m.ValidFrom
	}
	return 0
}

func (m *ZkOrder) GetValidUntil() uint64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *ZkOrder) GetSignature() *types.ZkSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// 限价订单
type SpotLimitOrder struct {
	// 交易对
	LeftAsset uint32 `protobuf:"varint,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 交易对
	RightAsset uint32 `protobuf:"varint,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 价格
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// 总量
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 操作， 1为买，2为卖
	Op                   int32    `protobuf:"varint,5,opt,name=op,proto3" json:"op,omitempty"`
	Order                *ZkOrder `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotLimitOrder) Reset()         { *m = SpotLimitOrder{} }
func (m *SpotLimitOrder) String() string { return proto.CompactTextString(m) }
func (*SpotLimitOrder) ProtoMessage()    {}
func (*SpotLimitOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{2}
}
func (m *SpotLimitOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotLimitOrder.Unmarshal(m, b)
}
func (m *SpotLimitOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotLimitOrder.Marshal(b, m, deterministic)
}
func (dst *SpotLimitOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotLimitOrder.Merge(dst, src)
}
func (m *SpotLimitOrder) XXX_Size() int {
	return xxx_messageInfo_SpotLimitOrder.Size(m)
}
func (m *SpotLimitOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotLimitOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SpotLimitOrder proto.InternalMessageInfo

func (m *SpotLimitOrder) GetLeftAsset() uint32 {
	if m != nil {
		return m.LeftAsset
	}
	return 0
}

func (m *SpotLimitOrder) GetRightAsset() uint32 {
	if m != nil {
		return m.RightAsset
	}
	return 0
}

func (m *SpotLimitOrder) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SpotLimitOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SpotLimitOrder) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *SpotLimitOrder) GetOrder() *ZkOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

// 市价委托
type SpotMarketOrder struct {
	// 资产1
	LeftAsset uint32 `protobuf:"varint,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 资产2
	RightAsset uint32 `protobuf:"varint,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 总量
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// 操作， 1为买，2为卖
	Op                   int32    `protobuf:"varint,4,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotMarketOrder) Reset()         { *m = SpotMarketOrder{} }
func (m *SpotMarketOrder) String() string { return proto.CompactTextString(m) }
func (*SpotMarketOrder) ProtoMessage()    {}
func (*SpotMarketOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{3}
}
func (m *SpotMarketOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotMarketOrder.Unmarshal(m, b)
}
func (m *SpotMarketOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotMarketOrder.Marshal(b, m, deterministic)
}
func (dst *SpotMarketOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotMarketOrder.Merge(dst, src)
}
func (m *SpotMarketOrder) XXX_Size() int {
	return xxx_messageInfo_SpotMarketOrder.Size(m)
}
func (m *SpotMarketOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotMarketOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SpotMarketOrder proto.InternalMessageInfo

func (m *SpotMarketOrder) GetLeftAsset() uint32 {
	if m != nil {
		return m.LeftAsset
	}
	return 0
}

func (m *SpotMarketOrder) GetRightAsset() uint32 {
	if m != nil {
		return m.RightAsset
	}
	return 0
}

func (m *SpotMarketOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SpotMarketOrder) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

type SpotExchangeBind struct {
	// 交易地址
	ExchangeAddress string `protobuf:"bytes,1,opt,name=exchangeAddress,proto3" json:"exchangeAddress,omitempty"`
	// 委托地址
	EntrustAddress       string   `protobuf:"bytes,2,opt,name=entrustAddress,proto3" json:"entrustAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotExchangeBind) Reset()         { *m = SpotExchangeBind{} }
func (m *SpotExchangeBind) String() string { return proto.CompactTextString(m) }
func (*SpotExchangeBind) ProtoMessage()    {}
func (*SpotExchangeBind) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{4}
}
func (m *SpotExchangeBind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotExchangeBind.Unmarshal(m, b)
}
func (m *SpotExchangeBind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotExchangeBind.Marshal(b, m, deterministic)
}
func (dst *SpotExchangeBind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotExchangeBind.Merge(dst, src)
}
func (m *SpotExchangeBind) XXX_Size() int {
	return xxx_messageInfo_SpotExchangeBind.Size(m)
}
func (m *SpotExchangeBind) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotExchangeBind.DiscardUnknown(m)
}

var xxx_messageInfo_SpotExchangeBind proto.InternalMessageInfo

func (m *SpotExchangeBind) GetExchangeAddress() string {
	if m != nil {
		return m.ExchangeAddress
	}
	return ""
}

func (m *SpotExchangeBind) GetEntrustAddress() string {
	if m != nil {
		return m.EntrustAddress
	}
	return ""
}

// 委托限价订单
type SpotEntrustOrder struct {
	// 交易对
	LeftAsset uint32 `protobuf:"varint,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 交易对
	RightAsset uint32 `protobuf:"varint,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 价格
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// 总量
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 操作， 1为买，2为卖
	Op int32 `protobuf:"varint,5,opt,name=op,proto3" json:"op,omitempty"`
	// 交易地址
	Addr                 string   `protobuf:"bytes,6,opt,name=addr,proto3" json:"addr,omitempty"`
	Order                *ZkOrder `protobuf:"bytes,7,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotEntrustOrder) Reset()         { *m = SpotEntrustOrder{} }
func (m *SpotEntrustOrder) String() string { return proto.CompactTextString(m) }
func (*SpotEntrustOrder) ProtoMessage()    {}
func (*SpotEntrustOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{5}
}
func (m *SpotEntrustOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotEntrustOrder.Unmarshal(m, b)
}
func (m *SpotEntrustOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotEntrustOrder.Marshal(b, m, deterministic)
}
func (dst *SpotEntrustOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotEntrustOrder.Merge(dst, src)
}
func (m *SpotEntrustOrder) XXX_Size() int {
	return xxx_messageInfo_SpotEntrustOrder.Size(m)
}
func (m *SpotEntrustOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotEntrustOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SpotEntrustOrder proto.InternalMessageInfo

func (m *SpotEntrustOrder) GetLeftAsset() uint32 {
	if m != nil {
		return m.LeftAsset
	}
	return 0
}

func (m *SpotEntrustOrder) GetRightAsset() uint32 {
	if m != nil {
		return m.RightAsset
	}
	return 0
}

func (m *SpotEntrustOrder) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SpotEntrustOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SpotEntrustOrder) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *SpotEntrustOrder) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *SpotEntrustOrder) GetOrder() *ZkOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

// 委托撤回订单
type SpotEntrustRevokeOrder struct {
	// 订单号
	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	// 交易地址
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotEntrustRevokeOrder) Reset()         { *m = SpotEntrustRevokeOrder{} }
func (m *SpotEntrustRevokeOrder) String() string { return proto.CompactTextString(m) }
func (*SpotEntrustRevokeOrder) ProtoMessage()    {}
func (*SpotEntrustRevokeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{6}
}
func (m *SpotEntrustRevokeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotEntrustRevokeOrder.Unmarshal(m, b)
}
func (m *SpotEntrustRevokeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotEntrustRevokeOrder.Marshal(b, m, deterministic)
}
func (dst *SpotEntrustRevokeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotEntrustRevokeOrder.Merge(dst, src)
}
func (m *SpotEntrustRevokeOrder) XXX_Size() int {
	return xxx_messageInfo_SpotEntrustRevokeOrder.Size(m)
}
func (m *SpotEntrustRevokeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotEntrustRevokeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SpotEntrustRevokeOrder proto.InternalMessageInfo

func (m *SpotEntrustRevokeOrder) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *SpotEntrustRevokeOrder) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 撤回订单
type SpotRevokeOrder struct {
	// 订单号
	OrderID              int64    `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotRevokeOrder) Reset()         { *m = SpotRevokeOrder{} }
func (m *SpotRevokeOrder) String() string { return proto.CompactTextString(m) }
func (*SpotRevokeOrder) ProtoMessage()    {}
func (*SpotRevokeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{7}
}
func (m *SpotRevokeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotRevokeOrder.Unmarshal(m, b)
}
func (m *SpotRevokeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotRevokeOrder.Marshal(b, m, deterministic)
}
func (dst *SpotRevokeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotRevokeOrder.Merge(dst, src)
}
func (m *SpotRevokeOrder) XXX_Size() int {
	return xxx_messageInfo_SpotRevokeOrder.Size(m)
}
func (m *SpotRevokeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotRevokeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SpotRevokeOrder proto.InternalMessageInfo

func (m *SpotRevokeOrder) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

// 订单信息
type SpotOrder struct {
	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*SpotOrder_LimitOrder
	//	*SpotOrder_MarketOrder
	Value isSpotOrder_Value `protobuf_oneof:"value"`
	// 挂单类型
	Ty int32 `protobuf:"varint,4,opt,name=ty,proto3" json:"ty,omitempty"`
	// 已经成交的数量
	Executed int64 `protobuf:"varint,5,opt,name=executed,proto3" json:"executed,omitempty"`
	// 成交均价
	AVGPrice int64 `protobuf:"varint,6,opt,name=AVG_price,json=AVGPrice,proto3" json:"AVG_price,omitempty"`
	// 余额
	Balance int64 `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	// 状态,0 挂单中ordered， 1 完成completed， 2撤回 revoked
	Status int32 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	// 用户地址
	Addr string `protobuf:"bytes,9,opt,name=addr,proto3" json:"addr,omitempty"`
	// 更新时间
	UpdateTime int64 `protobuf:"varint,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	// 索引
	Index int64 `protobuf:"varint,11,opt,name=index,proto3" json:"index,omitempty"`
	// 手续费率 (挂单)
	Rate int32 `protobuf:"varint,12,opt,name=rate,proto3" json:"rate,omitempty"`
	// 手续费
	DigestedFee int64 `protobuf:"varint,13,opt,name=digestedFee,proto3" json:"digestedFee,omitempty"`
	// 主动成交手续费
	TakerRate int32 `protobuf:"varint,14,opt,name=takerRate,proto3" json:"takerRate,omitempty"`
	// 挂单hash
	Hash string `protobuf:"bytes,15,opt,name=hash,proto3" json:"hash,omitempty"`
	// 撤单hash
	RevokeHash string `protobuf:"bytes,16,opt,name=revokeHash,proto3" json:"revokeHash,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,17,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 委托地址
	EntrustAddr string `protobuf:"bytes,18,opt,name=entrustAddr,proto3" json:"entrustAddr,omitempty"`
	// frozen fee
	FeeBalance           int64    `protobuf:"varint,19,opt,name=feeBalance,proto3" json:"feeBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotOrder) Reset()         { *m = SpotOrder{} }
func (m *SpotOrder) String() string { return proto.CompactTextString(m) }
func (*SpotOrder) ProtoMessage()    {}
func (*SpotOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{8}
}
func (m *SpotOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotOrder.Unmarshal(m, b)
}
func (m *SpotOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotOrder.Marshal(b, m, deterministic)
}
func (dst *SpotOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotOrder.Merge(dst, src)
}
func (m *SpotOrder) XXX_Size() int {
	return xxx_messageInfo_SpotOrder.Size(m)
}
func (m *SpotOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SpotOrder proto.InternalMessageInfo

func (m *SpotOrder) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type isSpotOrder_Value interface {
	isSpotOrder_Value()
}

type SpotOrder_LimitOrder struct {
	LimitOrder *SpotLimitOrder `protobuf:"bytes,2,opt,name=limitOrder,proto3,oneof"`
}

type SpotOrder_MarketOrder struct {
	MarketOrder *SpotMarketOrder `protobuf:"bytes,3,opt,name=marketOrder,proto3,oneof"`
}

func (*SpotOrder_LimitOrder) isSpotOrder_Value() {}

func (*SpotOrder_MarketOrder) isSpotOrder_Value() {}

func (m *SpotOrder) GetValue() isSpotOrder_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SpotOrder) GetLimitOrder() *SpotLimitOrder {
	if x, ok := m.GetValue().(*SpotOrder_LimitOrder); ok {
		return x.LimitOrder
	}
	return nil
}

func (m *SpotOrder) GetMarketOrder() *SpotMarketOrder {
	if x, ok := m.GetValue().(*SpotOrder_MarketOrder); ok {
		return x.MarketOrder
	}
	return nil
}

func (m *SpotOrder) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

func (m *SpotOrder) GetExecuted() int64 {
	if m != nil {
		return m.Executed
	}
	return 0
}

func (m *SpotOrder) GetAVGPrice() int64 {
	if m != nil {
		return m.AVGPrice
	}
	return 0
}

func (m *SpotOrder) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *SpotOrder) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SpotOrder) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *SpotOrder) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *SpotOrder) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SpotOrder) GetRate() int32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *SpotOrder) GetDigestedFee() int64 {
	if m != nil {
		return m.DigestedFee
	}
	return 0
}

func (m *SpotOrder) GetTakerRate() int32 {
	if m != nil {
		return m.TakerRate
	}
	return 0
}

func (m *SpotOrder) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *SpotOrder) GetRevokeHash() string {
	if m != nil {
		return m.RevokeHash
	}
	return ""
}

func (m *SpotOrder) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SpotOrder) GetEntrustAddr() string {
	if m != nil {
		return m.EntrustAddr
	}
	return ""
}

func (m *SpotOrder) GetFeeBalance() int64 {
	if m != nil {
		return m.FeeBalance
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SpotOrder) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SpotOrder_OneofMarshaler, _SpotOrder_OneofUnmarshaler, _SpotOrder_OneofSizer, []interface{}{
		(*SpotOrder_LimitOrder)(nil),
		(*SpotOrder_MarketOrder)(nil),
	}
}

func _SpotOrder_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SpotOrder)
	// value
	switch x := m.Value.(type) {
	case *SpotOrder_LimitOrder:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LimitOrder); err != nil {
			return err
		}
	case *SpotOrder_MarketOrder:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MarketOrder); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SpotOrder.Value has unexpected type %T", x)
	}
	return nil
}

func _SpotOrder_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SpotOrder)
	switch tag {
	case 2: // value.limitOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SpotLimitOrder)
		err := b.DecodeMessage(msg)
		m.Value = &SpotOrder_LimitOrder{msg}
		return true, err
	case 3: // value.marketOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SpotMarketOrder)
		err := b.DecodeMessage(msg)
		m.Value = &SpotOrder_MarketOrder{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SpotOrder_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SpotOrder)
	// value
	switch x := m.Value.(type) {
	case *SpotOrder_LimitOrder:
		s := proto.Size(x.LimitOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SpotOrder_MarketOrder:
		s := proto.Size(x.MarketOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 查询接口
type SpotQueryMarketDepth struct {
	// 资产1
	LeftAsset uint32 `protobuf:"varint,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 资产2
	RightAsset uint32 `protobuf:"varint,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 操作， 1为买，2为卖
	Op int32 `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"`
	// 这里用价格作为索引值
	PrimaryKey string `protobuf:"bytes,4,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	// 单页返回多少条记录，默认返回10条,为了系统安全最多单次只能返回20条
	Count                int32    `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotQueryMarketDepth) Reset()         { *m = SpotQueryMarketDepth{} }
func (m *SpotQueryMarketDepth) String() string { return proto.CompactTextString(m) }
func (*SpotQueryMarketDepth) ProtoMessage()    {}
func (*SpotQueryMarketDepth) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{9}
}
func (m *SpotQueryMarketDepth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotQueryMarketDepth.Unmarshal(m, b)
}
func (m *SpotQueryMarketDepth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotQueryMarketDepth.Marshal(b, m, deterministic)
}
func (dst *SpotQueryMarketDepth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotQueryMarketDepth.Merge(dst, src)
}
func (m *SpotQueryMarketDepth) XXX_Size() int {
	return xxx_messageInfo_SpotQueryMarketDepth.Size(m)
}
func (m *SpotQueryMarketDepth) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotQueryMarketDepth.DiscardUnknown(m)
}

var xxx_messageInfo_SpotQueryMarketDepth proto.InternalMessageInfo

func (m *SpotQueryMarketDepth) GetLeftAsset() uint32 {
	if m != nil {
		return m.LeftAsset
	}
	return 0
}

func (m *SpotQueryMarketDepth) GetRightAsset() uint32 {
	if m != nil {
		return m.RightAsset
	}
	return 0
}

func (m *SpotQueryMarketDepth) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *SpotQueryMarketDepth) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *SpotQueryMarketDepth) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 市场深度
type SpotMarketDepth struct {
	// 资产1
	LeftAsset uint32 `protobuf:"varint,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 资产2
	RightAsset uint32 `protobuf:"varint,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 价格
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// 总量
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 操作， 1为买，2为卖
	Op                   int32    `protobuf:"varint,5,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotMarketDepth) Reset()         { *m = SpotMarketDepth{} }
func (m *SpotMarketDepth) String() string { return proto.CompactTextString(m) }
func (*SpotMarketDepth) ProtoMessage()    {}
func (*SpotMarketDepth) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{10}
}
func (m *SpotMarketDepth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotMarketDepth.Unmarshal(m, b)
}
func (m *SpotMarketDepth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotMarketDepth.Marshal(b, m, deterministic)
}
func (dst *SpotMarketDepth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotMarketDepth.Merge(dst, src)
}
func (m *SpotMarketDepth) XXX_Size() int {
	return xxx_messageInfo_SpotMarketDepth.Size(m)
}
func (m *SpotMarketDepth) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotMarketDepth.DiscardUnknown(m)
}

var xxx_messageInfo_SpotMarketDepth proto.InternalMessageInfo

func (m *SpotMarketDepth) GetLeftAsset() uint32 {
	if m != nil {
		return m.LeftAsset
	}
	return 0
}

func (m *SpotMarketDepth) GetRightAsset() uint32 {
	if m != nil {
		return m.RightAsset
	}
	return 0
}

func (m *SpotMarketDepth) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SpotMarketDepth) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SpotMarketDepth) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

// 查询接口返回的市场深度列表
type SpotMarketDepthList struct {
	List                 []*SpotMarketDepth `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PrimaryKey           string             `protobuf:"bytes,2,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SpotMarketDepthList) Reset()         { *m = SpotMarketDepthList{} }
func (m *SpotMarketDepthList) String() string { return proto.CompactTextString(m) }
func (*SpotMarketDepthList) ProtoMessage()    {}
func (*SpotMarketDepthList) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{11}
}
func (m *SpotMarketDepthList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotMarketDepthList.Unmarshal(m, b)
}
func (m *SpotMarketDepthList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotMarketDepthList.Marshal(b, m, deterministic)
}
func (dst *SpotMarketDepthList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotMarketDepthList.Merge(dst, src)
}
func (m *SpotMarketDepthList) XXX_Size() int {
	return xxx_messageInfo_SpotMarketDepthList.Size(m)
}
func (m *SpotMarketDepthList) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotMarketDepthList.DiscardUnknown(m)
}

var xxx_messageInfo_SpotMarketDepthList proto.InternalMessageInfo

func (m *SpotMarketDepthList) GetList() []*SpotMarketDepth {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SpotMarketDepthList) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

// 查询最新得成交信息,外部接口
type SpotQueryHistoryOrderList struct {
	// 资产1
	LeftAsset uint32 `protobuf:"varint,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 资产2
	RightAsset uint32 `protobuf:"varint,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 索引值
	PrimaryKey string `protobuf:"bytes,3,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	// 单页返回多少条记录，默认返回10条,为了系统安全最多单次只能返回20条
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// 0降序，1升序，默认降序
	Direction            int32    `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotQueryHistoryOrderList) Reset()         { *m = SpotQueryHistoryOrderList{} }
func (m *SpotQueryHistoryOrderList) String() string { return proto.CompactTextString(m) }
func (*SpotQueryHistoryOrderList) ProtoMessage()    {}
func (*SpotQueryHistoryOrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{12}
}
func (m *SpotQueryHistoryOrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotQueryHistoryOrderList.Unmarshal(m, b)
}
func (m *SpotQueryHistoryOrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotQueryHistoryOrderList.Marshal(b, m, deterministic)
}
func (dst *SpotQueryHistoryOrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotQueryHistoryOrderList.Merge(dst, src)
}
func (m *SpotQueryHistoryOrderList) XXX_Size() int {
	return xxx_messageInfo_SpotQueryHistoryOrderList.Size(m)
}
func (m *SpotQueryHistoryOrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotQueryHistoryOrderList.DiscardUnknown(m)
}

var xxx_messageInfo_SpotQueryHistoryOrderList proto.InternalMessageInfo

func (m *SpotQueryHistoryOrderList) GetLeftAsset() uint32 {
	if m != nil {
		return m.LeftAsset
	}
	return 0
}

func (m *SpotQueryHistoryOrderList) GetRightAsset() uint32 {
	if m != nil {
		return m.RightAsset
	}
	return 0
}

func (m *SpotQueryHistoryOrderList) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *SpotQueryHistoryOrderList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SpotQueryHistoryOrderList) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

// 根据orderID去查询订单信息
type SpotQueryOrder struct {
	OrderID              int64    `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotQueryOrder) Reset()         { *m = SpotQueryOrder{} }
func (m *SpotQueryOrder) String() string { return proto.CompactTextString(m) }
func (*SpotQueryOrder) ProtoMessage()    {}
func (*SpotQueryOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{13}
}
func (m *SpotQueryOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotQueryOrder.Unmarshal(m, b)
}
func (m *SpotQueryOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotQueryOrder.Marshal(b, m, deterministic)
}
func (dst *SpotQueryOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotQueryOrder.Merge(dst, src)
}
func (m *SpotQueryOrder) XXX_Size() int {
	return xxx_messageInfo_SpotQueryOrder.Size(m)
}
func (m *SpotQueryOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotQueryOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SpotQueryOrder proto.InternalMessageInfo

func (m *SpotQueryOrder) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

// 根据地址，状态查询用户自己的挂单信息
type SpotQueryOrderList struct {
	// 挂单状态必填(默认是0,只查询ordered挂单中的)
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 用户地址信息，必填
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// 主键索引
	PrimaryKey string `protobuf:"bytes,3,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	// 单页返回多少条记录，默认返回10条,为了系统安全最多单次只能返回20条
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// 0降序，1升序，默认降序
	Direction            int32    `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotQueryOrderList) Reset()         { *m = SpotQueryOrderList{} }
func (m *SpotQueryOrderList) String() string { return proto.CompactTextString(m) }
func (*SpotQueryOrderList) ProtoMessage()    {}
func (*SpotQueryOrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{14}
}
func (m *SpotQueryOrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotQueryOrderList.Unmarshal(m, b)
}
func (m *SpotQueryOrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotQueryOrderList.Marshal(b, m, deterministic)
}
func (dst *SpotQueryOrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotQueryOrderList.Merge(dst, src)
}
func (m *SpotQueryOrderList) XXX_Size() int {
	return xxx_messageInfo_SpotQueryOrderList.Size(m)
}
func (m *SpotQueryOrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotQueryOrderList.DiscardUnknown(m)
}

var xxx_messageInfo_SpotQueryOrderList proto.InternalMessageInfo

func (m *SpotQueryOrderList) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SpotQueryOrderList) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SpotQueryOrderList) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *SpotQueryOrderList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SpotQueryOrderList) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

// 订单列表
type SpotOrderList struct {
	List                 []*SpotOrder `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PrimaryKey           string       `protobuf:"bytes,2,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SpotOrderList) Reset()         { *m = SpotOrderList{} }
func (m *SpotOrderList) String() string { return proto.CompactTextString(m) }
func (*SpotOrderList) ProtoMessage()    {}
func (*SpotOrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{15}
}
func (m *SpotOrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotOrderList.Unmarshal(m, b)
}
func (m *SpotOrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotOrderList.Marshal(b, m, deterministic)
}
func (dst *SpotOrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotOrderList.Merge(dst, src)
}
func (m *SpotOrderList) XXX_Size() int {
	return xxx_messageInfo_SpotOrderList.Size(m)
}
func (m *SpotOrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotOrderList.DiscardUnknown(m)
}

var xxx_messageInfo_SpotOrderList proto.InternalMessageInfo

func (m *SpotOrderList) GetList() []*SpotOrder {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SpotOrderList) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

// exchange执行票据日志
type ReceiptSpotMatch struct {
	Order                *SpotOrder   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	MatchOrders          []*SpotOrder `protobuf:"bytes,2,rep,name=matchOrders,proto3" json:"matchOrders,omitempty"`
	Index                int64        `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReceiptSpotMatch) Reset()         { *m = ReceiptSpotMatch{} }
func (m *ReceiptSpotMatch) String() string { return proto.CompactTextString(m) }
func (*ReceiptSpotMatch) ProtoMessage()    {}
func (*ReceiptSpotMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{16}
}
func (m *ReceiptSpotMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptSpotMatch.Unmarshal(m, b)
}
func (m *ReceiptSpotMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptSpotMatch.Marshal(b, m, deterministic)
}
func (dst *ReceiptSpotMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptSpotMatch.Merge(dst, src)
}
func (m *ReceiptSpotMatch) XXX_Size() int {
	return xxx_messageInfo_ReceiptSpotMatch.Size(m)
}
func (m *ReceiptSpotMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptSpotMatch.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptSpotMatch proto.InternalMessageInfo

func (m *ReceiptSpotMatch) GetOrder() *SpotOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *ReceiptSpotMatch) GetMatchOrders() []*SpotOrder {
	if m != nil {
		return m.MatchOrders
	}
	return nil
}

func (m *ReceiptSpotMatch) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ReceiptDexBind struct {
	// 交易地址
	ExchangeAddress string `protobuf:"bytes,1,opt,name=exchangeAddress,proto3" json:"exchangeAddress,omitempty"`
	// 委托地址
	NewEntrustAddress string `protobuf:"bytes,2,opt,name=newEntrustAddress,proto3" json:"newEntrustAddress,omitempty"`
	// 委托地址
	OldEntrustAddress    string   `protobuf:"bytes,3,opt,name=oldEntrustAddress,proto3" json:"oldEntrustAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptDexBind) Reset()         { *m = ReceiptDexBind{} }
func (m *ReceiptDexBind) String() string { return proto.CompactTextString(m) }
func (*ReceiptDexBind) ProtoMessage()    {}
func (*ReceiptDexBind) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{17}
}
func (m *ReceiptDexBind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptDexBind.Unmarshal(m, b)
}
func (m *ReceiptDexBind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptDexBind.Marshal(b, m, deterministic)
}
func (dst *ReceiptDexBind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptDexBind.Merge(dst, src)
}
func (m *ReceiptDexBind) XXX_Size() int {
	return xxx_messageInfo_ReceiptDexBind.Size(m)
}
func (m *ReceiptDexBind) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptDexBind.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptDexBind proto.InternalMessageInfo

func (m *ReceiptDexBind) GetExchangeAddress() string {
	if m != nil {
		return m.ExchangeAddress
	}
	return ""
}

func (m *ReceiptDexBind) GetNewEntrustAddress() string {
	if m != nil {
		return m.NewEntrustAddress
	}
	return ""
}

func (m *ReceiptDexBind) GetOldEntrustAddress() string {
	if m != nil {
		return m.OldEntrustAddress
	}
	return ""
}

// 每种代币的数量
type DexAccountBalance struct {
	// token id
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance              uint64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Frozen               uint64   `protobuf:"varint,3,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	DexName              string   `protobuf:"bytes,5,opt,name=dexName,proto3" json:"dexName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DexAccountBalance) Reset()         { *m = DexAccountBalance{} }
func (m *DexAccountBalance) String() string { return proto.CompactTextString(m) }
func (*DexAccountBalance) ProtoMessage()    {}
func (*DexAccountBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{18}
}
func (m *DexAccountBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DexAccountBalance.Unmarshal(m, b)
}
func (m *DexAccountBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DexAccountBalance.Marshal(b, m, deterministic)
}
func (dst *DexAccountBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexAccountBalance.Merge(dst, src)
}
func (m *DexAccountBalance) XXX_Size() int {
	return xxx_messageInfo_DexAccountBalance.Size(m)
}
func (m *DexAccountBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_DexAccountBalance.DiscardUnknown(m)
}

var xxx_messageInfo_DexAccountBalance proto.InternalMessageInfo

func (m *DexAccountBalance) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DexAccountBalance) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *DexAccountBalance) GetFrozen() uint64 {
	if m != nil {
		return m.Frozen
	}
	return 0
}

func (m *DexAccountBalance) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DexAccountBalance) GetDexName() string {
	if m != nil {
		return m.DexName
	}
	return ""
}

// 用户代币的数量
type DexAccount struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr                 string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Balance              []*DexAccountBalance `protobuf:"bytes,3,rep,name=balance,proto3" json:"balance,omitempty"`
	DexName              string               `protobuf:"bytes,4,opt,name=dexName,proto3" json:"dexName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DexAccount) Reset()         { *m = DexAccount{} }
func (m *DexAccount) String() string { return proto.CompactTextString(m) }
func (*DexAccount) ProtoMessage()    {}
func (*DexAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{19}
}
func (m *DexAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DexAccount.Unmarshal(m, b)
}
func (m *DexAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DexAccount.Marshal(b, m, deterministic)
}
func (dst *DexAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexAccount.Merge(dst, src)
}
func (m *DexAccount) XXX_Size() int {
	return xxx_messageInfo_DexAccount.Size(m)
}
func (m *DexAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DexAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DexAccount proto.InternalMessageInfo

func (m *DexAccount) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DexAccount) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DexAccount) GetBalance() []*DexAccountBalance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *DexAccount) GetDexName() string {
	if m != nil {
		return m.DexName
	}
	return ""
}

type TradeAccounts struct {
	Taker                *DexAccount `protobuf:"bytes,1,opt,name=taker,proto3" json:"taker,omitempty"`
	Maker                *DexAccount `protobuf:"bytes,2,opt,name=maker,proto3" json:"maker,omitempty"`
	Fee                  *DexAccount `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TradeAccounts) Reset()         { *m = TradeAccounts{} }
func (m *TradeAccounts) String() string { return proto.CompactTextString(m) }
func (*TradeAccounts) ProtoMessage()    {}
func (*TradeAccounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{20}
}
func (m *TradeAccounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeAccounts.Unmarshal(m, b)
}
func (m *TradeAccounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeAccounts.Marshal(b, m, deterministic)
}
func (dst *TradeAccounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeAccounts.Merge(dst, src)
}
func (m *TradeAccounts) XXX_Size() int {
	return xxx_messageInfo_TradeAccounts.Size(m)
}
func (m *TradeAccounts) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeAccounts.DiscardUnknown(m)
}

var xxx_messageInfo_TradeAccounts proto.InternalMessageInfo

func (m *TradeAccounts) GetTaker() *DexAccount {
	if m != nil {
		return m.Taker
	}
	return nil
}

func (m *TradeAccounts) GetMaker() *DexAccount {
	if m != nil {
		return m.Maker
	}
	return nil
}

func (m *TradeAccounts) GetFee() *DexAccount {
	if m != nil {
		return m.Fee
	}
	return nil
}

type MatchInfo struct {
	// trade match balance
	Matched     int64 `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	LeftBalance int64 `protobuf:"varint,2,opt,name=leftBalance,proto3" json:"leftBalance,omitempty"`
	// = matched * price
	RightBalance int64 `protobuf:"varint,3,opt,name=rightBalance,proto3" json:"rightBalance,omitempty"`
	// fee use right token
	FeeTaker             int64    `protobuf:"varint,4,opt,name=feeTaker,proto3" json:"feeTaker,omitempty"`
	FeeMater             int64    `protobuf:"varint,5,opt,name=feeMater,proto3" json:"feeMater,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchInfo) Reset()         { *m = MatchInfo{} }
func (m *MatchInfo) String() string { return proto.CompactTextString(m) }
func (*MatchInfo) ProtoMessage()    {}
func (*MatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{21}
}
func (m *MatchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchInfo.Unmarshal(m, b)
}
func (m *MatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchInfo.Marshal(b, m, deterministic)
}
func (dst *MatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchInfo.Merge(dst, src)
}
func (m *MatchInfo) XXX_Size() int {
	return xxx_messageInfo_MatchInfo.Size(m)
}
func (m *MatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MatchInfo proto.InternalMessageInfo

func (m *MatchInfo) GetMatched() int64 {
	if m != nil {
		return m.Matched
	}
	return 0
}

func (m *MatchInfo) GetLeftBalance() int64 {
	if m != nil {
		return m.LeftBalance
	}
	return 0
}

func (m *MatchInfo) GetRightBalance() int64 {
	if m != nil {
		return m.RightBalance
	}
	return 0
}

func (m *MatchInfo) GetFeeTaker() int64 {
	if m != nil {
		return m.FeeTaker
	}
	return 0
}

func (m *MatchInfo) GetFeeMater() int64 {
	if m != nil {
		return m.FeeMater
	}
	return 0
}

type ReceiptSpotTrade struct {
	Match                *MatchInfo     `protobuf:"bytes,1,opt,name=Match,proto3" json:"Match,omitempty"`
	Prev                 *TradeAccounts `protobuf:"bytes,2,opt,name=prev,proto3" json:"prev,omitempty"`
	Current              *TradeAccounts `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReceiptSpotTrade) Reset()         { *m = ReceiptSpotTrade{} }
func (m *ReceiptSpotTrade) String() string { return proto.CompactTextString(m) }
func (*ReceiptSpotTrade) ProtoMessage()    {}
func (*ReceiptSpotTrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{22}
}
func (m *ReceiptSpotTrade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptSpotTrade.Unmarshal(m, b)
}
func (m *ReceiptSpotTrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptSpotTrade.Marshal(b, m, deterministic)
}
func (dst *ReceiptSpotTrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptSpotTrade.Merge(dst, src)
}
func (m *ReceiptSpotTrade) XXX_Size() int {
	return xxx_messageInfo_ReceiptSpotTrade.Size(m)
}
func (m *ReceiptSpotTrade) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptSpotTrade.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptSpotTrade proto.InternalMessageInfo

func (m *ReceiptSpotTrade) GetMatch() *MatchInfo {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *ReceiptSpotTrade) GetPrev() *TradeAccounts {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *ReceiptSpotTrade) GetCurrent() *TradeAccounts {
	if m != nil {
		return m.Current
	}
	return nil
}

type ReceiptDexAccount struct {
	Prev                 *DexAccount `protobuf:"bytes,1,opt,name=prev,proto3" json:"prev,omitempty"`
	Current              *DexAccount `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReceiptDexAccount) Reset()         { *m = ReceiptDexAccount{} }
func (m *ReceiptDexAccount) String() string { return proto.CompactTextString(m) }
func (*ReceiptDexAccount) ProtoMessage()    {}
func (*ReceiptDexAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_442b6ff8ea939d3e, []int{23}
}
func (m *ReceiptDexAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptDexAccount.Unmarshal(m, b)
}
func (m *ReceiptDexAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptDexAccount.Marshal(b, m, deterministic)
}
func (dst *ReceiptDexAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptDexAccount.Merge(dst, src)
}
func (m *ReceiptDexAccount) XXX_Size() int {
	return xxx_messageInfo_ReceiptDexAccount.Size(m)
}
func (m *ReceiptDexAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptDexAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptDexAccount proto.InternalMessageInfo

func (m *ReceiptDexAccount) GetPrev() *DexAccount {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *ReceiptDexAccount) GetCurrent() *DexAccount {
	if m != nil {
		return m.Current
	}
	return nil
}

func init() {
	proto.RegisterType((*SpotAction)(nil), "types.SpotAction")
	proto.RegisterType((*ZkOrder)(nil), "types.ZkOrder")
	proto.RegisterType((*SpotLimitOrder)(nil), "types.SpotLimitOrder")
	proto.RegisterType((*SpotMarketOrder)(nil), "types.SpotMarketOrder")
	proto.RegisterType((*SpotExchangeBind)(nil), "types.SpotExchangeBind")
	proto.RegisterType((*SpotEntrustOrder)(nil), "types.SpotEntrustOrder")
	proto.RegisterType((*SpotEntrustRevokeOrder)(nil), "types.SpotEntrustRevokeOrder")
	proto.RegisterType((*SpotRevokeOrder)(nil), "types.SpotRevokeOrder")
	proto.RegisterType((*SpotOrder)(nil), "types.SpotOrder")
	proto.RegisterType((*SpotQueryMarketDepth)(nil), "types.SpotQueryMarketDepth")
	proto.RegisterType((*SpotMarketDepth)(nil), "types.SpotMarketDepth")
	proto.RegisterType((*SpotMarketDepthList)(nil), "types.SpotMarketDepthList")
	proto.RegisterType((*SpotQueryHistoryOrderList)(nil), "types.SpotQueryHistoryOrderList")
	proto.RegisterType((*SpotQueryOrder)(nil), "types.SpotQueryOrder")
	proto.RegisterType((*SpotQueryOrderList)(nil), "types.SpotQueryOrderList")
	proto.RegisterType((*SpotOrderList)(nil), "types.SpotOrderList")
	proto.RegisterType((*ReceiptSpotMatch)(nil), "types.ReceiptSpotMatch")
	proto.RegisterType((*ReceiptDexBind)(nil), "types.ReceiptDexBind")
	proto.RegisterType((*DexAccountBalance)(nil), "types.DexAccountBalance")
	proto.RegisterType((*DexAccount)(nil), "types.DexAccount")
	proto.RegisterType((*TradeAccounts)(nil), "types.TradeAccounts")
	proto.RegisterType((*MatchInfo)(nil), "types.MatchInfo")
	proto.RegisterType((*ReceiptSpotTrade)(nil), "types.ReceiptSpotTrade")
	proto.RegisterType((*ReceiptDexAccount)(nil), "types.ReceiptDexAccount")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZkspotClient is the client API for Zkspot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZkspotClient interface {
}

type zkspotClient struct {
	cc *grpc.ClientConn
}

func NewZkspotClient(cc *grpc.ClientConn) ZkspotClient {
	return &zkspotClient{cc}
}

// ZkspotServer is the server API for Zkspot service.
type ZkspotServer interface {
}

func RegisterZkspotServer(s *grpc.Server, srv ZkspotServer) {
	s.RegisterService(&_Zkspot_serviceDesc, srv)
}

var _Zkspot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.zkspot",
	HandlerType: (*ZkspotServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "spot.proto",
}

func init() { proto.RegisterFile("spot.proto", fileDescriptor_spot_442b6ff8ea939d3e) }

var fileDescriptor_spot_442b6ff8ea939d3e = []byte{
	// 1358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcf, 0x6f, 0x1b, 0xc5,
	0x17, 0xef, 0xfe, 0x70, 0x5c, 0xbf, 0xd4, 0x6e, 0x32, 0xcd, 0xb7, 0xdf, 0xa5, 0x40, 0x55, 0x2d,
	0xa5, 0x44, 0x2d, 0x4a, 0x68, 0x7a, 0x40, 0x42, 0xe2, 0x10, 0x2b, 0x6d, 0x53, 0xd1, 0x52, 0x98,
	0xfe, 0x38, 0xf4, 0x82, 0xb6, 0xbb, 0x2f, 0xf6, 0xca, 0xf6, 0xee, 0x6a, 0x77, 0x9c, 0xc4, 0x3d,
	0x70, 0x01, 0x71, 0xe3, 0x86, 0x38, 0xf4, 0x8a, 0x38, 0x72, 0xe1, 0xaf, 0xe0, 0x86, 0xc4, 0x5f,
	0x84, 0xe6, 0xcd, 0xec, 0xee, 0xac, 0xed, 0xd0, 0x96, 0x80, 0x38, 0xd5, 0xef, 0xd7, 0xcc, 0x67,
	0xde, 0xe7, 0xfd, 0xd8, 0x14, 0xa0, 0xc8, 0x52, 0xb1, 0x95, 0xe5, 0xa9, 0x48, 0x59, 0x4b, 0xcc,
	0x32, 0x2c, 0x2e, 0x75, 0x8f, 0x62, 0x91, 0x60, 0x51, 0x28, 0xad, 0xff, 0xb3, 0x03, 0xf0, 0x28,
	0x4b, 0xc5, 0x6e, 0x28, 0xe2, 0x34, 0x61, 0x1f, 0x03, 0x8c, 0xe3, 0x49, 0x2c, 0x1e, 0xe6, 0x11,
	0xe6, 0x9e, 0x75, 0xc5, 0xda, 0x5c, 0xdd, 0xf9, 0xdf, 0x16, 0x45, 0x6e, 0x49, 0xb7, 0xfb, 0x95,
	0x71, 0xff, 0x0c, 0x37, 0x5c, 0xd9, 0x27, 0xb0, 0x3a, 0x09, 0xf2, 0x11, 0xea, 0x48, 0x9b, 0x22,
	0x2f, 0x1a, 0x91, 0x0f, 0x6a, 0xeb, 0xfe, 0x19, 0x6e, 0x3a, 0xcb, 0xd8, 0x1c, 0x0f, 0xd3, 0x11,
	0xaa, 0x58, 0x67, 0x21, 0x96, 0xd7, 0x56, 0x19, 0x6b, 0x38, 0xb3, 0x4f, 0xe1, 0x1c, 0x1e, 0x87,
	0xc3, 0x20, 0x19, 0x60, 0x3f, 0x4e, 0x22, 0xcf, 0xa5, 0xe0, 0xff, 0x1b, 0xc1, 0xb7, 0x0d, 0xf3,
	0xfe, 0x19, 0xde, 0x70, 0xa7, 0xf0, 0x44, 0xe4, 0xd3, 0x42, 0xe3, 0x6e, 0x2d, 0x86, 0x1b, 0x66,
	0x0a, 0x37, 0x64, 0xf6, 0x10, 0x98, 0x96, 0x0d, 0x88, 0x5e, 0x9b, 0x0e, 0x79, 0x77, 0xf1, 0x90,
	0xe6, 0x3b, 0x96, 0x84, 0xb2, 0x1e, 0xd8, 0x62, 0xe6, 0xad, 0x5c, 0xb1, 0x36, 0x5b, 0xdc, 0x16,
	0xb3, 0x7e, 0x1b, 0x5a, 0x87, 0xc1, 0x78, 0x8a, 0xfe, 0xef, 0x36, 0xb4, 0x9f, 0x8d, 0x94, 0xd3,
	0x3b, 0xd0, 0x09, 0xc2, 0x30, 0x9d, 0x26, 0xe2, 0xde, 0x1e, 0x71, 0xe4, 0xf2, 0x5a, 0xc1, 0x2e,
	0x03, 0xa0, 0x18, 0xee, 0x46, 0x51, 0x8e, 0x45, 0x41, 0x44, 0x74, 0xb8, 0xa1, 0x61, 0x1b, 0xd0,
	0x4a, 0xd2, 0x24, 0x44, 0xca, 0xb3, 0xcb, 0x95, 0x20, 0xcf, 0x14, 0xe9, 0x08, 0x93, 0x47, 0x38,
	0x1e, 0x53, 0x12, 0xbb, 0xbc, 0x56, 0xb0, 0x4b, 0x70, 0x96, 0x84, 0xfe, 0x74, 0x46, 0x29, 0xea,
	0xf2, 0x4a, 0x66, 0x17, 0x61, 0x25, 0x98, 0xc8, 0xbb, 0x09, 0xb6, 0xcb, 0xb5, 0x24, 0xf5, 0x79,
	0x20, 0xe2, 0xf4, 0x26, 0xe5, 0xa3, 0xcb, 0xb5, 0x54, 0xe9, 0x77, 0xbc, 0xb3, 0x86, 0x7e, 0x47,
	0x22, 0x38, 0x0c, 0xc6, 0x71, 0x74, 0x27, 0x4f, 0x27, 0x5e, 0x47, 0xbd, 0xaa, 0x52, 0xc8, 0x57,
	0x91, 0xf0, 0x24, 0x11, 0xf1, 0xd8, 0x03, 0x32, 0x1b, 0x1a, 0xf6, 0x11, 0x74, 0x8a, 0x78, 0x90,
	0x04, 0x62, 0x9a, 0xa3, 0xb7, 0x41, 0x04, 0x30, 0x4d, 0xc0, 0xb3, 0xd1, 0xa3, 0xd2, 0xc2, 0x6b,
	0x27, 0xff, 0x57, 0x0b, 0x7a, 0xcd, 0x92, 0x96, 0x10, 0xc6, 0x78, 0x20, 0x76, 0x8b, 0x02, 0x05,
	0x25, 0xb6, 0xcb, 0x6b, 0x85, 0x84, 0x90, 0xc7, 0x83, 0xa1, 0x36, 0xdb, 0x64, 0x36, 0x34, 0x32,
	0xb1, 0x59, 0x1e, 0xeb, 0xc4, 0x3a, 0x5c, 0x09, 0x46, 0x7a, 0x5c, 0x52, 0x97, 0xe9, 0xe9, 0x81,
	0x9d, 0x66, 0x94, 0xcc, 0x16, 0xb7, 0xd3, 0x8c, 0x5d, 0x85, 0x56, 0x4a, 0xd5, 0xb3, 0x42, 0xe0,
	0x7b, 0x15, 0x78, 0x82, 0xc6, 0x95, 0xd1, 0x3f, 0x82, 0xf3, 0x73, 0xcd, 0x74, 0x4a, 0xd0, 0x35,
	0x3c, 0x67, 0x09, 0x3c, 0xb7, 0x84, 0xe7, 0x47, 0xb0, 0x36, 0xdf, 0x4c, 0x6c, 0x13, 0xce, 0x97,
	0xcd, 0x54, 0x96, 0x9b, 0x45, 0xe5, 0x36, 0xaf, 0x66, 0xd7, 0xa0, 0xa7, 0x8b, 0xbd, 0x59, 0x97,
	0x73, 0x5a, 0xff, 0x37, 0x4b, 0x5f, 0x63, 0x36, 0xd9, 0x7f, 0xc9, 0x0a, 0x03, 0x37, 0x88, 0x22,
	0x45, 0x4a, 0x87, 0xd3, 0xef, 0x9a, 0xa9, 0xf6, 0x5f, 0x31, 0x75, 0x07, 0x2e, 0x2e, 0xef, 0x7c,
	0xe6, 0x41, 0x9b, 0x5c, 0x74, 0xf3, 0x3a, 0xbc, 0x14, 0xab, 0xdb, 0xec, 0xfa, 0x36, 0xff, 0x86,
	0x62, 0xfc, 0xb5, 0x0e, 0xf0, 0xff, 0x70, 0xa1, 0x23, 0xbd, 0x5f, 0x75, 0x51, 0x73, 0xcc, 0xdb,
	0x7f, 0x7b, 0xcc, 0x3b, 0x6f, 0x32, 0xe6, 0xd5, 0x6c, 0x73, 0xcb, 0xd9, 0x26, 0x87, 0x0a, 0x1e,
	0x63, 0x38, 0x15, 0x18, 0x51, 0xc6, 0x1d, 0x5e, 0xc9, 0xec, 0x6d, 0xe8, 0xec, 0x3e, 0xbd, 0xfb,
	0x95, 0x62, 0x6e, 0x45, 0x19, 0x77, 0x9f, 0xde, 0xfd, 0x82, 0xc8, 0xf3, 0xa0, 0xfd, 0x3c, 0x18,
	0x07, 0x72, 0x86, 0xb5, 0xd5, 0xbb, 0xb4, 0x28, 0x69, 0x2d, 0x44, 0x20, 0xa6, 0x05, 0xcd, 0x96,
	0x16, 0xd7, 0x52, 0x95, 0xd8, 0x8e, 0x41, 0xe3, 0x65, 0x80, 0x69, 0x16, 0x05, 0x02, 0x1f, 0xc7,
	0x13, 0xa4, 0x89, 0xe2, 0x70, 0x43, 0x23, 0x0b, 0x27, 0x4e, 0x22, 0x3c, 0xf6, 0x56, 0x55, 0xe1,
	0x90, 0x20, 0x4f, 0xca, 0x03, 0x81, 0xde, 0x39, 0x3a, 0x9f, 0x7e, 0xb3, 0x2b, 0xb0, 0x1a, 0xc5,
	0x03, 0x2c, 0x04, 0x46, 0x77, 0x10, 0xbd, 0x2e, 0xf9, 0x9b, 0x2a, 0x9a, 0xae, 0xc1, 0x08, 0x73,
	0x2e, 0x43, 0x7b, 0x14, 0x5a, 0x2b, 0xe4, 0x99, 0xc3, 0xa0, 0x18, 0x7a, 0xe7, 0x15, 0x3a, 0xf9,
	0x9b, 0xca, 0x9a, 0x28, 0xdf, 0x97, 0x96, 0x35, 0x35, 0xc5, 0x6b, 0x8d, 0xb4, 0x87, 0x39, 0x96,
	0xe8, 0xd7, 0x15, 0xfa, 0x5a, 0x23, 0x31, 0x19, 0xbd, 0xe5, 0x31, 0x3a, 0xc0, 0x54, 0xc9, 0x13,
	0x0e, 0x10, 0xfb, 0x3a, 0x91, 0x17, 0xd4, 0x09, 0xb5, 0xa6, 0x5e, 0x3d, 0x2f, 0x2d, 0xd8, 0x90,
	0xd4, 0x7e, 0x39, 0xc5, 0x7c, 0xa6, 0xf8, 0xdd, 0xc3, 0x4c, 0x0c, 0x4f, 0xd9, 0x98, 0xaa, 0xd5,
	0x9c, 0xaa, 0xd5, 0x2e, 0x03, 0x64, 0x79, 0x3c, 0x09, 0xf2, 0xd9, 0x67, 0xa8, 0xca, 0xa4, 0xc3,
	0x0d, 0x8d, 0xe4, 0x83, 0x56, 0x9c, 0xee, 0x4e, 0x25, 0xf8, 0xdf, 0x5b, 0xe6, 0x44, 0xfc, 0x27,
	0x70, 0x9d, 0x6a, 0x60, 0xf8, 0x01, 0x5c, 0x98, 0x83, 0x73, 0x3f, 0x2e, 0x04, 0xbb, 0x0e, 0xee,
	0x38, 0x2e, 0x24, 0x1a, 0x67, 0x69, 0xc3, 0x90, 0x27, 0x27, 0x9f, 0xb9, 0x44, 0xd8, 0xf3, 0x89,
	0xf0, 0x7f, 0xb1, 0xe0, 0xad, 0x8a, 0x8f, 0xfd, 0xb8, 0x10, 0x69, 0x3e, 0xa3, 0x0e, 0xa3, 0x9b,
	0x4e, 0xf7, 0xf8, 0xe6, 0xdd, 0xce, 0xc9, 0x24, 0xb8, 0x06, 0x09, 0xf2, 0xce, 0x28, 0xce, 0x91,
	0x3e, 0x21, 0x75, 0x2e, 0x6a, 0x85, 0x7f, 0x5d, 0xed, 0x59, 0x82, 0xfb, 0xaa, 0x01, 0xf6, 0xd2,
	0x02, 0xd6, 0x74, 0xa6, 0x47, 0xd5, 0x7d, 0x6d, 0x35, 0xfa, 0xda, 0x83, 0x76, 0xd0, 0x58, 0x28,
	0xa5, 0xf8, 0xaf, 0x3c, 0xe4, 0x09, 0x74, 0xab, 0xe1, 0x4a, 0xb0, 0xae, 0x36, 0x58, 0x5d, 0x33,
	0x58, 0x55, 0xab, 0xe0, 0xf5, 0xf8, 0xfc, 0xd6, 0x82, 0x35, 0x8e, 0x21, 0xc6, 0x99, 0x50, 0x05,
	0x21, 0xc2, 0x21, 0xbb, 0x56, 0x2e, 0x19, 0xf5, 0x0d, 0xbe, 0x78, 0xb6, 0x32, 0xb3, 0x1d, 0x39,
	0x90, 0x45, 0x38, 0x24, 0xa5, 0xcc, 0xc2, 0x72, 0x24, 0xa6, 0x53, 0x3d, 0xd9, 0x1c, 0x63, 0xb2,
	0xf9, 0x3f, 0x5a, 0xd0, 0xd3, 0x30, 0xf6, 0xf0, 0xf8, 0x0d, 0x17, 0xfc, 0x87, 0xb0, 0x9e, 0xe0,
	0xd1, 0xed, 0x65, 0x3b, 0x7e, 0xd1, 0x20, 0xbd, 0xd3, 0x71, 0x34, 0xe7, 0xad, 0x38, 0x5a, 0x34,
	0xf8, 0xdf, 0x58, 0xb0, 0xbe, 0x87, 0xc7, 0xbb, 0xea, 0x0b, 0x57, 0x8f, 0x27, 0xd9, 0x78, 0x71,
	0xa4, 0x0b, 0xdc, 0x8e, 0x23, 0x73, 0x29, 0xd8, 0xf4, 0x75, 0x68, 0x2e, 0x85, 0x83, 0x3c, 0x7d,
	0x81, 0x89, 0xfe, 0xe2, 0xd5, 0x52, 0xb5, 0x14, 0x5c, 0x63, 0x29, 0x78, 0xd0, 0x8e, 0xf0, 0xf8,
	0xf3, 0x60, 0x82, 0x44, 0x7f, 0x87, 0x97, 0xa2, 0xff, 0x35, 0x40, 0x0d, 0xc2, 0xb8, 0xdd, 0xa5,
	0xdb, 0x97, 0x6c, 0x6e, 0xb6, 0x53, 0x23, 0x72, 0x88, 0x16, 0x4f, 0xd3, 0xb2, 0xf0, 0x98, 0x1a,
	0xab, 0x71, 0xbf, 0xdb, 0xbc, 0xff, 0x3b, 0x0b, 0xba, 0x8f, 0xf3, 0x20, 0x42, 0x1d, 0x5a, 0xb0,
	0x0f, 0xa0, 0x45, 0x3b, 0x44, 0x97, 0xc8, 0xfa, 0xc2, 0xe9, 0x5c, 0xd9, 0xa5, 0xe3, 0x84, 0x1c,
	0xed, 0x13, 0x1d, 0xc9, 0xce, 0xde, 0x03, 0xe7, 0x00, 0x51, 0x6f, 0xf5, 0x25, 0x6e, 0xd2, 0xea,
	0xff, 0x64, 0x41, 0x87, 0x6a, 0xf4, 0x5e, 0x72, 0x90, 0x4a, 0xc0, 0x54, 0x5a, 0x18, 0x95, 0xad,
	0xac, 0x45, 0xb9, 0x81, 0xe4, 0xdc, 0xe9, 0x1b, 0xa4, 0x38, 0xdc, 0x54, 0x31, 0x1f, 0xce, 0xd1,
	0xe8, 0xe9, 0x57, 0x59, 0x92, 0x2e, 0x0d, 0x9d, 0xfc, 0x48, 0x38, 0x40, 0x7c, 0x4c, 0xf0, 0xd5,
	0xe4, 0xad, 0x64, 0x6d, 0x7b, 0x10, 0x08, 0xfd, 0x87, 0x9b, 0xb2, 0x91, 0xec, 0xff, 0xd0, 0x6c,
	0x2a, 0xca, 0x9c, 0x6c, 0x2a, 0x42, 0x3e, 0xd7, 0x54, 0xd5, 0x6b, 0xb8, 0x32, 0xb3, 0x4d, 0x70,
	0xb3, 0x1c, 0x0f, 0x75, 0xbe, 0x36, 0xb4, 0x5b, 0x23, 0xfb, 0x9c, 0x3c, 0xd8, 0x16, 0xb4, 0xc3,
	0x69, 0x9e, 0xa3, 0xfe, 0x7e, 0x3e, 0xc9, 0xb9, 0x74, 0xf2, 0x07, 0xb0, 0x5e, 0xf7, 0x58, 0x59,
	0x4c, 0xef, 0xeb, 0xeb, 0x4e, 0xe4, 0x51, 0xdd, 0x75, 0xa3, 0xbe, 0xeb, 0x44, 0x22, 0x4b, 0x8f,
	0x9d, 0xb3, 0xb0, 0xf2, 0x62, 0x24, 0xff, 0xfa, 0xef, 0xdf, 0x7c, 0xb6, 0x3d, 0x88, 0xc5, 0x70,
	0xfa, 0x7c, 0x2b, 0x4c, 0x27, 0xdb, 0xb7, 0x6e, 0x85, 0xc9, 0x76, 0x36, 0x9e, 0x0e, 0xe2, 0xea,
	0x9f, 0x28, 0xc8, 0xb2, 0x6d, 0xe5, 0xbc, 0x4d, 0x07, 0x3e, 0x5f, 0xa1, 0xff, 0x1b, 0xb8, 0xf5,
	0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xca, 0xe2, 0x50, 0x3f, 0x10, 0x00, 0x00,
}
