// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spot.proto

package types // import "github.com/33cn/plugin/plugin/dapp/zkspot/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Exchange struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{0}
}
func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exchange.Unmarshal(m, b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
}
func (dst *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(dst, src)
}
func (m *Exchange) XXX_Size() int {
	return xxx_messageInfo_Exchange.Size(m)
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

type ExchangeAction struct {
	// Types that are valid to be assigned to Value:
	//	*ExchangeAction_LimitOrder
	//	*ExchangeAction_MarketOrder
	//	*ExchangeAction_RevokeOrder
	//	*ExchangeAction_ExchangeBind
	//	*ExchangeAction_EntrustOrder
	//	*ExchangeAction_EntrustRevokeOrder
	Value                isExchangeAction_Value `protobuf_oneof:"value"`
	Ty                   int32                  `protobuf:"varint,6,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ExchangeAction) Reset()         { *m = ExchangeAction{} }
func (m *ExchangeAction) String() string { return proto.CompactTextString(m) }
func (*ExchangeAction) ProtoMessage()    {}
func (*ExchangeAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{1}
}
func (m *ExchangeAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeAction.Unmarshal(m, b)
}
func (m *ExchangeAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeAction.Marshal(b, m, deterministic)
}
func (dst *ExchangeAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeAction.Merge(dst, src)
}
func (m *ExchangeAction) XXX_Size() int {
	return xxx_messageInfo_ExchangeAction.Size(m)
}
func (m *ExchangeAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeAction.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeAction proto.InternalMessageInfo

type isExchangeAction_Value interface {
	isExchangeAction_Value()
}

type ExchangeAction_LimitOrder struct {
	LimitOrder *LimitOrder `protobuf:"bytes,1,opt,name=limitOrder,proto3,oneof"`
}

type ExchangeAction_MarketOrder struct {
	MarketOrder *MarketOrder `protobuf:"bytes,2,opt,name=marketOrder,proto3,oneof"`
}

type ExchangeAction_RevokeOrder struct {
	RevokeOrder *RevokeOrder `protobuf:"bytes,3,opt,name=revokeOrder,proto3,oneof"`
}

type ExchangeAction_ExchangeBind struct {
	ExchangeBind *ExchangeBind `protobuf:"bytes,4,opt,name=exchangeBind,proto3,oneof"`
}

type ExchangeAction_EntrustOrder struct {
	EntrustOrder *EntrustOrder `protobuf:"bytes,5,opt,name=entrustOrder,proto3,oneof"`
}

type ExchangeAction_EntrustRevokeOrder struct {
	EntrustRevokeOrder *EntrustRevokeOrder `protobuf:"bytes,7,opt,name=entrustRevokeOrder,proto3,oneof"`
}

func (*ExchangeAction_LimitOrder) isExchangeAction_Value() {}

func (*ExchangeAction_MarketOrder) isExchangeAction_Value() {}

func (*ExchangeAction_RevokeOrder) isExchangeAction_Value() {}

func (*ExchangeAction_ExchangeBind) isExchangeAction_Value() {}

func (*ExchangeAction_EntrustOrder) isExchangeAction_Value() {}

func (*ExchangeAction_EntrustRevokeOrder) isExchangeAction_Value() {}

func (m *ExchangeAction) GetValue() isExchangeAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ExchangeAction) GetLimitOrder() *LimitOrder {
	if x, ok := m.GetValue().(*ExchangeAction_LimitOrder); ok {
		return x.LimitOrder
	}
	return nil
}

func (m *ExchangeAction) GetMarketOrder() *MarketOrder {
	if x, ok := m.GetValue().(*ExchangeAction_MarketOrder); ok {
		return x.MarketOrder
	}
	return nil
}

func (m *ExchangeAction) GetRevokeOrder() *RevokeOrder {
	if x, ok := m.GetValue().(*ExchangeAction_RevokeOrder); ok {
		return x.RevokeOrder
	}
	return nil
}

func (m *ExchangeAction) GetExchangeBind() *ExchangeBind {
	if x, ok := m.GetValue().(*ExchangeAction_ExchangeBind); ok {
		return x.ExchangeBind
	}
	return nil
}

func (m *ExchangeAction) GetEntrustOrder() *EntrustOrder {
	if x, ok := m.GetValue().(*ExchangeAction_EntrustOrder); ok {
		return x.EntrustOrder
	}
	return nil
}

func (m *ExchangeAction) GetEntrustRevokeOrder() *EntrustRevokeOrder {
	if x, ok := m.GetValue().(*ExchangeAction_EntrustRevokeOrder); ok {
		return x.EntrustRevokeOrder
	}
	return nil
}

func (m *ExchangeAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ExchangeAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ExchangeAction_OneofMarshaler, _ExchangeAction_OneofUnmarshaler, _ExchangeAction_OneofSizer, []interface{}{
		(*ExchangeAction_LimitOrder)(nil),
		(*ExchangeAction_MarketOrder)(nil),
		(*ExchangeAction_RevokeOrder)(nil),
		(*ExchangeAction_ExchangeBind)(nil),
		(*ExchangeAction_EntrustOrder)(nil),
		(*ExchangeAction_EntrustRevokeOrder)(nil),
	}
}

func _ExchangeAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ExchangeAction)
	// value
	switch x := m.Value.(type) {
	case *ExchangeAction_LimitOrder:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LimitOrder); err != nil {
			return err
		}
	case *ExchangeAction_MarketOrder:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MarketOrder); err != nil {
			return err
		}
	case *ExchangeAction_RevokeOrder:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RevokeOrder); err != nil {
			return err
		}
	case *ExchangeAction_ExchangeBind:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExchangeBind); err != nil {
			return err
		}
	case *ExchangeAction_EntrustOrder:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EntrustOrder); err != nil {
			return err
		}
	case *ExchangeAction_EntrustRevokeOrder:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EntrustRevokeOrder); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ExchangeAction.Value has unexpected type %T", x)
	}
	return nil
}

func _ExchangeAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ExchangeAction)
	switch tag {
	case 1: // value.limitOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LimitOrder)
		err := b.DecodeMessage(msg)
		m.Value = &ExchangeAction_LimitOrder{msg}
		return true, err
	case 2: // value.marketOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MarketOrder)
		err := b.DecodeMessage(msg)
		m.Value = &ExchangeAction_MarketOrder{msg}
		return true, err
	case 3: // value.revokeOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RevokeOrder)
		err := b.DecodeMessage(msg)
		m.Value = &ExchangeAction_RevokeOrder{msg}
		return true, err
	case 4: // value.exchangeBind
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExchangeBind)
		err := b.DecodeMessage(msg)
		m.Value = &ExchangeAction_ExchangeBind{msg}
		return true, err
	case 5: // value.entrustOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EntrustOrder)
		err := b.DecodeMessage(msg)
		m.Value = &ExchangeAction_EntrustOrder{msg}
		return true, err
	case 7: // value.entrustRevokeOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EntrustRevokeOrder)
		err := b.DecodeMessage(msg)
		m.Value = &ExchangeAction_EntrustRevokeOrder{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ExchangeAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ExchangeAction)
	// value
	switch x := m.Value.(type) {
	case *ExchangeAction_LimitOrder:
		s := proto.Size(x.LimitOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ExchangeAction_MarketOrder:
		s := proto.Size(x.MarketOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ExchangeAction_RevokeOrder:
		s := proto.Size(x.RevokeOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ExchangeAction_ExchangeBind:
		s := proto.Size(x.ExchangeBind)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ExchangeAction_EntrustOrder:
		s := proto.Size(x.EntrustOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ExchangeAction_EntrustRevokeOrder:
		s := proto.Size(x.EntrustRevokeOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ZkOrder struct {
	AccountID            uint64       `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	EthAddress           string       `protobuf:"bytes,2,opt,name=ethAddress,proto3" json:"ethAddress,omitempty"`
	Nonce                uint64       `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TokenSell            uint32       `protobuf:"varint,4,opt,name=tokenSell,proto3" json:"tokenSell,omitempty"`
	TokenBuy             uint32       `protobuf:"varint,5,opt,name=tokenBuy,proto3" json:"tokenBuy,omitempty"`
	Amount               uint64       `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Ratio1               uint32       `protobuf:"varint,7,opt,name=ratio1,proto3" json:"ratio1,omitempty"`
	Ratio2               uint32       `protobuf:"varint,8,opt,name=ratio2,proto3" json:"ratio2,omitempty"`
	ValidFrom            uint64       `protobuf:"varint,9,opt,name=validFrom,proto3" json:"validFrom,omitempty"`
	ValidUntil           uint64       `protobuf:"varint,10,opt,name=validUntil,proto3" json:"validUntil,omitempty"`
	Signature            *ZkSignature `protobuf:"bytes,20,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ZkOrder) Reset()         { *m = ZkOrder{} }
func (m *ZkOrder) String() string { return proto.CompactTextString(m) }
func (*ZkOrder) ProtoMessage()    {}
func (*ZkOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{2}
}
func (m *ZkOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZkOrder.Unmarshal(m, b)
}
func (m *ZkOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZkOrder.Marshal(b, m, deterministic)
}
func (dst *ZkOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZkOrder.Merge(dst, src)
}
func (m *ZkOrder) XXX_Size() int {
	return xxx_messageInfo_ZkOrder.Size(m)
}
func (m *ZkOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ZkOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ZkOrder proto.InternalMessageInfo

func (m *ZkOrder) GetAccountID() uint64 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *ZkOrder) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *ZkOrder) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ZkOrder) GetTokenSell() uint32 {
	if m != nil {
		return m.TokenSell
	}
	return 0
}

func (m *ZkOrder) GetTokenBuy() uint32 {
	if m != nil {
		return m.TokenBuy
	}
	return 0
}

func (m *ZkOrder) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ZkOrder) GetRatio1() uint32 {
	if m != nil {
		return m.Ratio1
	}
	return 0
}

func (m *ZkOrder) GetRatio2() uint32 {
	if m != nil {
		return m.Ratio2
	}
	return 0
}

func (m *ZkOrder) GetValidFrom() uint64 {
	if m != nil {
		return m.ValidFrom
	}
	return 0
}

func (m *ZkOrder) GetValidUntil() uint64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *ZkOrder) GetSignature() *ZkSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// 限价订单
type LimitOrder struct {
	// 交易对
	LeftAsset uint32 `protobuf:"varint,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 交易对
	RightAsset uint32 `protobuf:"varint,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 价格
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// 总量
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 操作， 1为买，2为卖
	Op                   int32    `protobuf:"varint,5,opt,name=op,proto3" json:"op,omitempty"`
	Order                *ZkOrder `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitOrder) Reset()         { *m = LimitOrder{} }
func (m *LimitOrder) String() string { return proto.CompactTextString(m) }
func (*LimitOrder) ProtoMessage()    {}
func (*LimitOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{3}
}
func (m *LimitOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitOrder.Unmarshal(m, b)
}
func (m *LimitOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitOrder.Marshal(b, m, deterministic)
}
func (dst *LimitOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitOrder.Merge(dst, src)
}
func (m *LimitOrder) XXX_Size() int {
	return xxx_messageInfo_LimitOrder.Size(m)
}
func (m *LimitOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitOrder.DiscardUnknown(m)
}

var xxx_messageInfo_LimitOrder proto.InternalMessageInfo

func (m *LimitOrder) GetLeftAsset() uint32 {
	if m != nil {
		return m.LeftAsset
	}
	return 0
}

func (m *LimitOrder) GetRightAsset() uint32 {
	if m != nil {
		return m.RightAsset
	}
	return 0
}

func (m *LimitOrder) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *LimitOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *LimitOrder) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *LimitOrder) GetOrder() *ZkOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

// 市价委托
type MarketOrder struct {
	// 资产1
	LeftAsset *Asset `protobuf:"bytes,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 资产2
	RightAsset *Asset `protobuf:"bytes,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 总量
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// 操作， 1为买，2为卖
	Op                   int32    `protobuf:"varint,4,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketOrder) Reset()         { *m = MarketOrder{} }
func (m *MarketOrder) String() string { return proto.CompactTextString(m) }
func (*MarketOrder) ProtoMessage()    {}
func (*MarketOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{4}
}
func (m *MarketOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketOrder.Unmarshal(m, b)
}
func (m *MarketOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketOrder.Marshal(b, m, deterministic)
}
func (dst *MarketOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketOrder.Merge(dst, src)
}
func (m *MarketOrder) XXX_Size() int {
	return xxx_messageInfo_MarketOrder.Size(m)
}
func (m *MarketOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MarketOrder proto.InternalMessageInfo

func (m *MarketOrder) GetLeftAsset() *Asset {
	if m != nil {
		return m.LeftAsset
	}
	return nil
}

func (m *MarketOrder) GetRightAsset() *Asset {
	if m != nil {
		return m.RightAsset
	}
	return nil
}

func (m *MarketOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MarketOrder) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

type ExchangeBind struct {
	// 交易地址
	ExchangeAddress string `protobuf:"bytes,1,opt,name=exchangeAddress,proto3" json:"exchangeAddress,omitempty"`
	// 委托地址
	EntrustAddress       string   `protobuf:"bytes,2,opt,name=entrustAddress,proto3" json:"entrustAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeBind) Reset()         { *m = ExchangeBind{} }
func (m *ExchangeBind) String() string { return proto.CompactTextString(m) }
func (*ExchangeBind) ProtoMessage()    {}
func (*ExchangeBind) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{5}
}
func (m *ExchangeBind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeBind.Unmarshal(m, b)
}
func (m *ExchangeBind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeBind.Marshal(b, m, deterministic)
}
func (dst *ExchangeBind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeBind.Merge(dst, src)
}
func (m *ExchangeBind) XXX_Size() int {
	return xxx_messageInfo_ExchangeBind.Size(m)
}
func (m *ExchangeBind) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeBind.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeBind proto.InternalMessageInfo

func (m *ExchangeBind) GetExchangeAddress() string {
	if m != nil {
		return m.ExchangeAddress
	}
	return ""
}

func (m *ExchangeBind) GetEntrustAddress() string {
	if m != nil {
		return m.EntrustAddress
	}
	return ""
}

// 委托限价订单
type EntrustOrder struct {
	// 交易对
	LeftAsset uint32 `protobuf:"varint,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 交易对
	RightAsset uint32 `protobuf:"varint,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 价格
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// 总量
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 操作， 1为买，2为卖
	Op int32 `protobuf:"varint,5,opt,name=op,proto3" json:"op,omitempty"`
	// 交易地址
	Addr                 string   `protobuf:"bytes,6,opt,name=addr,proto3" json:"addr,omitempty"`
	Order                *ZkOrder `protobuf:"bytes,7,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntrustOrder) Reset()         { *m = EntrustOrder{} }
func (m *EntrustOrder) String() string { return proto.CompactTextString(m) }
func (*EntrustOrder) ProtoMessage()    {}
func (*EntrustOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{6}
}
func (m *EntrustOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntrustOrder.Unmarshal(m, b)
}
func (m *EntrustOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntrustOrder.Marshal(b, m, deterministic)
}
func (dst *EntrustOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntrustOrder.Merge(dst, src)
}
func (m *EntrustOrder) XXX_Size() int {
	return xxx_messageInfo_EntrustOrder.Size(m)
}
func (m *EntrustOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_EntrustOrder.DiscardUnknown(m)
}

var xxx_messageInfo_EntrustOrder proto.InternalMessageInfo

func (m *EntrustOrder) GetLeftAsset() uint32 {
	if m != nil {
		return m.LeftAsset
	}
	return 0
}

func (m *EntrustOrder) GetRightAsset() uint32 {
	if m != nil {
		return m.RightAsset
	}
	return 0
}

func (m *EntrustOrder) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *EntrustOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *EntrustOrder) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *EntrustOrder) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *EntrustOrder) GetOrder() *ZkOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

// 委托撤回订单
type EntrustRevokeOrder struct {
	// 订单号
	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	// 交易地址
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntrustRevokeOrder) Reset()         { *m = EntrustRevokeOrder{} }
func (m *EntrustRevokeOrder) String() string { return proto.CompactTextString(m) }
func (*EntrustRevokeOrder) ProtoMessage()    {}
func (*EntrustRevokeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{7}
}
func (m *EntrustRevokeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntrustRevokeOrder.Unmarshal(m, b)
}
func (m *EntrustRevokeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntrustRevokeOrder.Marshal(b, m, deterministic)
}
func (dst *EntrustRevokeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntrustRevokeOrder.Merge(dst, src)
}
func (m *EntrustRevokeOrder) XXX_Size() int {
	return xxx_messageInfo_EntrustRevokeOrder.Size(m)
}
func (m *EntrustRevokeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_EntrustRevokeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_EntrustRevokeOrder proto.InternalMessageInfo

func (m *EntrustRevokeOrder) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *EntrustRevokeOrder) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// 撤回订单
type RevokeOrder struct {
	// 订单号
	OrderID              int64    `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeOrder) Reset()         { *m = RevokeOrder{} }
func (m *RevokeOrder) String() string { return proto.CompactTextString(m) }
func (*RevokeOrder) ProtoMessage()    {}
func (*RevokeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{8}
}
func (m *RevokeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeOrder.Unmarshal(m, b)
}
func (m *RevokeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeOrder.Marshal(b, m, deterministic)
}
func (dst *RevokeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeOrder.Merge(dst, src)
}
func (m *RevokeOrder) XXX_Size() int {
	return xxx_messageInfo_RevokeOrder.Size(m)
}
func (m *RevokeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeOrder proto.InternalMessageInfo

func (m *RevokeOrder) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

// 资产类型
type Asset struct {
	Execer               string   `protobuf:"bytes,1,opt,name=execer,proto3" json:"execer,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{9}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (dst *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(dst, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetExecer() string {
	if m != nil {
		return m.Execer
	}
	return ""
}

func (m *Asset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

// 订单信息
type Order struct {
	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Order_LimitOrder
	//	*Order_MarketOrder
	Value isOrder_Value `protobuf_oneof:"value"`
	// 挂单类型
	Ty int32 `protobuf:"varint,4,opt,name=ty,proto3" json:"ty,omitempty"`
	// 已经成交的数量
	Executed int64 `protobuf:"varint,5,opt,name=executed,proto3" json:"executed,omitempty"`
	// 成交均价
	AVGPrice int64 `protobuf:"varint,6,opt,name=AVG_price,json=AVGPrice,proto3" json:"AVG_price,omitempty"`
	// 余额
	Balance int64 `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	// 状态,0 挂单中ordered， 1 完成completed， 2撤回 revoked
	Status int32 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	// 用户地址
	Addr string `protobuf:"bytes,9,opt,name=addr,proto3" json:"addr,omitempty"`
	// 更新时间
	UpdateTime int64 `protobuf:"varint,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	// 索引
	Index int64 `protobuf:"varint,11,opt,name=index,proto3" json:"index,omitempty"`
	// 手续费率 (挂单)
	Rate int32 `protobuf:"varint,12,opt,name=rate,proto3" json:"rate,omitempty"`
	// 手续费
	DigestedFee int64 `protobuf:"varint,13,opt,name=digestedFee,proto3" json:"digestedFee,omitempty"`
	// 最小手续费
	MinFee int64 `protobuf:"varint,14,opt,name=minFee,proto3" json:"minFee,omitempty"`
	// 挂单hash
	Hash string `protobuf:"bytes,15,opt,name=hash,proto3" json:"hash,omitempty"`
	// 撤单hash
	RevokeHash string `protobuf:"bytes,16,opt,name=revokeHash,proto3" json:"revokeHash,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,17,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 委托地址
	EntrustAddr string `protobuf:"bytes,18,opt,name=entrustAddr,proto3" json:"entrustAddr,omitempty"`
	// frozen fee
	FeeBalance           int64    `protobuf:"varint,19,opt,name=feeBalance,proto3" json:"feeBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{10}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type isOrder_Value interface {
	isOrder_Value()
}

type Order_LimitOrder struct {
	LimitOrder *LimitOrder `protobuf:"bytes,2,opt,name=limitOrder,proto3,oneof"`
}

type Order_MarketOrder struct {
	MarketOrder *MarketOrder `protobuf:"bytes,3,opt,name=marketOrder,proto3,oneof"`
}

func (*Order_LimitOrder) isOrder_Value() {}

func (*Order_MarketOrder) isOrder_Value() {}

func (m *Order) GetValue() isOrder_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Order) GetLimitOrder() *LimitOrder {
	if x, ok := m.GetValue().(*Order_LimitOrder); ok {
		return x.LimitOrder
	}
	return nil
}

func (m *Order) GetMarketOrder() *MarketOrder {
	if x, ok := m.GetValue().(*Order_MarketOrder); ok {
		return x.MarketOrder
	}
	return nil
}

func (m *Order) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

func (m *Order) GetExecuted() int64 {
	if m != nil {
		return m.Executed
	}
	return 0
}

func (m *Order) GetAVGPrice() int64 {
	if m != nil {
		return m.AVGPrice
	}
	return 0
}

func (m *Order) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Order) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Order) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Order) GetRate() int32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Order) GetDigestedFee() int64 {
	if m != nil {
		return m.DigestedFee
	}
	return 0
}

func (m *Order) GetMinFee() int64 {
	if m != nil {
		return m.MinFee
	}
	return 0
}

func (m *Order) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Order) GetRevokeHash() string {
	if m != nil {
		return m.RevokeHash
	}
	return ""
}

func (m *Order) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Order) GetEntrustAddr() string {
	if m != nil {
		return m.EntrustAddr
	}
	return ""
}

func (m *Order) GetFeeBalance() int64 {
	if m != nil {
		return m.FeeBalance
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Order) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Order_OneofMarshaler, _Order_OneofUnmarshaler, _Order_OneofSizer, []interface{}{
		(*Order_LimitOrder)(nil),
		(*Order_MarketOrder)(nil),
	}
}

func _Order_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Order)
	// value
	switch x := m.Value.(type) {
	case *Order_LimitOrder:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LimitOrder); err != nil {
			return err
		}
	case *Order_MarketOrder:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MarketOrder); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Order.Value has unexpected type %T", x)
	}
	return nil
}

func _Order_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Order)
	switch tag {
	case 2: // value.limitOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LimitOrder)
		err := b.DecodeMessage(msg)
		m.Value = &Order_LimitOrder{msg}
		return true, err
	case 3: // value.marketOrder
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MarketOrder)
		err := b.DecodeMessage(msg)
		m.Value = &Order_MarketOrder{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Order_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Order)
	// value
	switch x := m.Value.(type) {
	case *Order_LimitOrder:
		s := proto.Size(x.LimitOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Order_MarketOrder:
		s := proto.Size(x.MarketOrder)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 查询接口
type QueryMarketDepth struct {
	// 资产1
	LeftAsset *Asset `protobuf:"bytes,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 资产2
	RightAsset *Asset `protobuf:"bytes,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 操作， 1为买，2为卖
	Op int32 `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"`
	// 这里用价格作为索引值
	PrimaryKey string `protobuf:"bytes,4,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	// 单页返回多少条记录，默认返回10条,为了系统安全最多单次只能返回20条
	Count                int32    `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryMarketDepth) Reset()         { *m = QueryMarketDepth{} }
func (m *QueryMarketDepth) String() string { return proto.CompactTextString(m) }
func (*QueryMarketDepth) ProtoMessage()    {}
func (*QueryMarketDepth) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{11}
}
func (m *QueryMarketDepth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryMarketDepth.Unmarshal(m, b)
}
func (m *QueryMarketDepth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryMarketDepth.Marshal(b, m, deterministic)
}
func (dst *QueryMarketDepth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketDepth.Merge(dst, src)
}
func (m *QueryMarketDepth) XXX_Size() int {
	return xxx_messageInfo_QueryMarketDepth.Size(m)
}
func (m *QueryMarketDepth) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketDepth.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketDepth proto.InternalMessageInfo

func (m *QueryMarketDepth) GetLeftAsset() *Asset {
	if m != nil {
		return m.LeftAsset
	}
	return nil
}

func (m *QueryMarketDepth) GetRightAsset() *Asset {
	if m != nil {
		return m.RightAsset
	}
	return nil
}

func (m *QueryMarketDepth) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *QueryMarketDepth) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *QueryMarketDepth) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 市场深度
type MarketDepth struct {
	// 资产1
	LeftAsset *Asset `protobuf:"bytes,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 资产2
	RightAsset *Asset `protobuf:"bytes,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 价格
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// 总量
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 操作， 1为买，2为卖
	Op                   int32    `protobuf:"varint,5,opt,name=op,proto3" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketDepth) Reset()         { *m = MarketDepth{} }
func (m *MarketDepth) String() string { return proto.CompactTextString(m) }
func (*MarketDepth) ProtoMessage()    {}
func (*MarketDepth) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{12}
}
func (m *MarketDepth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDepth.Unmarshal(m, b)
}
func (m *MarketDepth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDepth.Marshal(b, m, deterministic)
}
func (dst *MarketDepth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDepth.Merge(dst, src)
}
func (m *MarketDepth) XXX_Size() int {
	return xxx_messageInfo_MarketDepth.Size(m)
}
func (m *MarketDepth) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDepth.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDepth proto.InternalMessageInfo

func (m *MarketDepth) GetLeftAsset() *Asset {
	if m != nil {
		return m.LeftAsset
	}
	return nil
}

func (m *MarketDepth) GetRightAsset() *Asset {
	if m != nil {
		return m.RightAsset
	}
	return nil
}

func (m *MarketDepth) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MarketDepth) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MarketDepth) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

// 查询接口返回的市场深度列表
type MarketDepthList struct {
	List                 []*MarketDepth `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PrimaryKey           string         `protobuf:"bytes,2,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MarketDepthList) Reset()         { *m = MarketDepthList{} }
func (m *MarketDepthList) String() string { return proto.CompactTextString(m) }
func (*MarketDepthList) ProtoMessage()    {}
func (*MarketDepthList) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{13}
}
func (m *MarketDepthList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDepthList.Unmarshal(m, b)
}
func (m *MarketDepthList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDepthList.Marshal(b, m, deterministic)
}
func (dst *MarketDepthList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDepthList.Merge(dst, src)
}
func (m *MarketDepthList) XXX_Size() int {
	return xxx_messageInfo_MarketDepthList.Size(m)
}
func (m *MarketDepthList) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDepthList.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDepthList proto.InternalMessageInfo

func (m *MarketDepthList) GetList() []*MarketDepth {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *MarketDepthList) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

// 查询最新得成交信息,外部接口
type QueryHistoryOrderList struct {
	// 资产1
	LeftAsset *Asset `protobuf:"bytes,1,opt,name=leftAsset,proto3" json:"leftAsset,omitempty"`
	// 资产2
	RightAsset *Asset `protobuf:"bytes,2,opt,name=rightAsset,proto3" json:"rightAsset,omitempty"`
	// 索引值
	PrimaryKey string `protobuf:"bytes,3,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	// 单页返回多少条记录，默认返回10条,为了系统安全最多单次只能返回20条
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// 0降序，1升序，默认降序
	Direction            int32    `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryHistoryOrderList) Reset()         { *m = QueryHistoryOrderList{} }
func (m *QueryHistoryOrderList) String() string { return proto.CompactTextString(m) }
func (*QueryHistoryOrderList) ProtoMessage()    {}
func (*QueryHistoryOrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{14}
}
func (m *QueryHistoryOrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryHistoryOrderList.Unmarshal(m, b)
}
func (m *QueryHistoryOrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryHistoryOrderList.Marshal(b, m, deterministic)
}
func (dst *QueryHistoryOrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHistoryOrderList.Merge(dst, src)
}
func (m *QueryHistoryOrderList) XXX_Size() int {
	return xxx_messageInfo_QueryHistoryOrderList.Size(m)
}
func (m *QueryHistoryOrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHistoryOrderList.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHistoryOrderList proto.InternalMessageInfo

func (m *QueryHistoryOrderList) GetLeftAsset() *Asset {
	if m != nil {
		return m.LeftAsset
	}
	return nil
}

func (m *QueryHistoryOrderList) GetRightAsset() *Asset {
	if m != nil {
		return m.RightAsset
	}
	return nil
}

func (m *QueryHistoryOrderList) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *QueryHistoryOrderList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryHistoryOrderList) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

// 根据orderID去查询订单信息
type QueryOrder struct {
	OrderID              int64    `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrder) Reset()         { *m = QueryOrder{} }
func (m *QueryOrder) String() string { return proto.CompactTextString(m) }
func (*QueryOrder) ProtoMessage()    {}
func (*QueryOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{15}
}
func (m *QueryOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrder.Unmarshal(m, b)
}
func (m *QueryOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrder.Marshal(b, m, deterministic)
}
func (dst *QueryOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrder.Merge(dst, src)
}
func (m *QueryOrder) XXX_Size() int {
	return xxx_messageInfo_QueryOrder.Size(m)
}
func (m *QueryOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrder.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrder proto.InternalMessageInfo

func (m *QueryOrder) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

// 根据地址，状态查询用户自己的挂单信息
type QueryOrderList struct {
	// 挂单状态必填(默认是0,只查询ordered挂单中的)
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 用户地址信息，必填
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// 主键索引
	PrimaryKey string `protobuf:"bytes,3,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	// 单页返回多少条记录，默认返回10条,为了系统安全最多单次只能返回20条
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// 0降序，1升序，默认降序
	Direction            int32    `protobuf:"varint,5,opt,name=direction,proto3" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryOrderList) Reset()         { *m = QueryOrderList{} }
func (m *QueryOrderList) String() string { return proto.CompactTextString(m) }
func (*QueryOrderList) ProtoMessage()    {}
func (*QueryOrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{16}
}
func (m *QueryOrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOrderList.Unmarshal(m, b)
}
func (m *QueryOrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOrderList.Marshal(b, m, deterministic)
}
func (dst *QueryOrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOrderList.Merge(dst, src)
}
func (m *QueryOrderList) XXX_Size() int {
	return xxx_messageInfo_QueryOrderList.Size(m)
}
func (m *QueryOrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOrderList.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOrderList proto.InternalMessageInfo

func (m *QueryOrderList) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *QueryOrderList) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryOrderList) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

func (m *QueryOrderList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryOrderList) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

// 订单列表
type OrderList struct {
	List                 []*Order `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PrimaryKey           string   `protobuf:"bytes,2,opt,name=primaryKey,proto3" json:"primaryKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderList) Reset()         { *m = OrderList{} }
func (m *OrderList) String() string { return proto.CompactTextString(m) }
func (*OrderList) ProtoMessage()    {}
func (*OrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{17}
}
func (m *OrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderList.Unmarshal(m, b)
}
func (m *OrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderList.Marshal(b, m, deterministic)
}
func (dst *OrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderList.Merge(dst, src)
}
func (m *OrderList) XXX_Size() int {
	return xxx_messageInfo_OrderList.Size(m)
}
func (m *OrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderList.DiscardUnknown(m)
}

var xxx_messageInfo_OrderList proto.InternalMessageInfo

func (m *OrderList) GetList() []*Order {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *OrderList) GetPrimaryKey() string {
	if m != nil {
		return m.PrimaryKey
	}
	return ""
}

// exchange执行票据日志
type ReceiptExchange struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	MatchOrders          []*Order `protobuf:"bytes,2,rep,name=matchOrders,proto3" json:"matchOrders,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptExchange) Reset()         { *m = ReceiptExchange{} }
func (m *ReceiptExchange) String() string { return proto.CompactTextString(m) }
func (*ReceiptExchange) ProtoMessage()    {}
func (*ReceiptExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{18}
}
func (m *ReceiptExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptExchange.Unmarshal(m, b)
}
func (m *ReceiptExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptExchange.Marshal(b, m, deterministic)
}
func (dst *ReceiptExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptExchange.Merge(dst, src)
}
func (m *ReceiptExchange) XXX_Size() int {
	return xxx_messageInfo_ReceiptExchange.Size(m)
}
func (m *ReceiptExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptExchange.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptExchange proto.InternalMessageInfo

func (m *ReceiptExchange) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *ReceiptExchange) GetMatchOrders() []*Order {
	if m != nil {
		return m.MatchOrders
	}
	return nil
}

func (m *ReceiptExchange) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ReceiptExchangeBind struct {
	// 交易地址
	ExchangeAddress string `protobuf:"bytes,1,opt,name=exchangeAddress,proto3" json:"exchangeAddress,omitempty"`
	// 委托地址
	NewEntrustAddress string `protobuf:"bytes,2,opt,name=newEntrustAddress,proto3" json:"newEntrustAddress,omitempty"`
	// 委托地址
	OldEntrustAddress    string   `protobuf:"bytes,3,opt,name=oldEntrustAddress,proto3" json:"oldEntrustAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiptExchangeBind) Reset()         { *m = ReceiptExchangeBind{} }
func (m *ReceiptExchangeBind) String() string { return proto.CompactTextString(m) }
func (*ReceiptExchangeBind) ProtoMessage()    {}
func (*ReceiptExchangeBind) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{19}
}
func (m *ReceiptExchangeBind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptExchangeBind.Unmarshal(m, b)
}
func (m *ReceiptExchangeBind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptExchangeBind.Marshal(b, m, deterministic)
}
func (dst *ReceiptExchangeBind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptExchangeBind.Merge(dst, src)
}
func (m *ReceiptExchangeBind) XXX_Size() int {
	return xxx_messageInfo_ReceiptExchangeBind.Size(m)
}
func (m *ReceiptExchangeBind) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptExchangeBind.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptExchangeBind proto.InternalMessageInfo

func (m *ReceiptExchangeBind) GetExchangeAddress() string {
	if m != nil {
		return m.ExchangeAddress
	}
	return ""
}

func (m *ReceiptExchangeBind) GetNewEntrustAddress() string {
	if m != nil {
		return m.NewEntrustAddress
	}
	return ""
}

func (m *ReceiptExchangeBind) GetOldEntrustAddress() string {
	if m != nil {
		return m.OldEntrustAddress
	}
	return ""
}

// 每种代币的数量
type DexAccountBalance struct {
	// token id
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance              uint64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Frozen               uint64   `protobuf:"varint,3,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	DexName              string   `protobuf:"bytes,5,opt,name=dexName,proto3" json:"dexName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DexAccountBalance) Reset()         { *m = DexAccountBalance{} }
func (m *DexAccountBalance) String() string { return proto.CompactTextString(m) }
func (*DexAccountBalance) ProtoMessage()    {}
func (*DexAccountBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{20}
}
func (m *DexAccountBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DexAccountBalance.Unmarshal(m, b)
}
func (m *DexAccountBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DexAccountBalance.Marshal(b, m, deterministic)
}
func (dst *DexAccountBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexAccountBalance.Merge(dst, src)
}
func (m *DexAccountBalance) XXX_Size() int {
	return xxx_messageInfo_DexAccountBalance.Size(m)
}
func (m *DexAccountBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_DexAccountBalance.DiscardUnknown(m)
}

var xxx_messageInfo_DexAccountBalance proto.InternalMessageInfo

func (m *DexAccountBalance) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DexAccountBalance) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *DexAccountBalance) GetFrozen() uint64 {
	if m != nil {
		return m.Frozen
	}
	return 0
}

func (m *DexAccountBalance) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DexAccountBalance) GetDexName() string {
	if m != nil {
		return m.DexName
	}
	return ""
}

// 用户代币的数量
type DexAccount struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr                 string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Balance              []*DexAccountBalance `protobuf:"bytes,3,rep,name=balance,proto3" json:"balance,omitempty"`
	DexName              string               `protobuf:"bytes,4,opt,name=dexName,proto3" json:"dexName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DexAccount) Reset()         { *m = DexAccount{} }
func (m *DexAccount) String() string { return proto.CompactTextString(m) }
func (*DexAccount) ProtoMessage()    {}
func (*DexAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_spot_18062e3d09ef4ab5, []int{21}
}
func (m *DexAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DexAccount.Unmarshal(m, b)
}
func (m *DexAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DexAccount.Marshal(b, m, deterministic)
}
func (dst *DexAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexAccount.Merge(dst, src)
}
func (m *DexAccount) XXX_Size() int {
	return xxx_messageInfo_DexAccount.Size(m)
}
func (m *DexAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_DexAccount.DiscardUnknown(m)
}

var xxx_messageInfo_DexAccount proto.InternalMessageInfo

func (m *DexAccount) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DexAccount) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *DexAccount) GetBalance() []*DexAccountBalance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *DexAccount) GetDexName() string {
	if m != nil {
		return m.DexName
	}
	return ""
}

func init() {
	proto.RegisterType((*Exchange)(nil), "types.Exchange")
	proto.RegisterType((*ExchangeAction)(nil), "types.ExchangeAction")
	proto.RegisterType((*ZkOrder)(nil), "types.ZkOrder")
	proto.RegisterType((*LimitOrder)(nil), "types.LimitOrder")
	proto.RegisterType((*MarketOrder)(nil), "types.MarketOrder")
	proto.RegisterType((*ExchangeBind)(nil), "types.ExchangeBind")
	proto.RegisterType((*EntrustOrder)(nil), "types.EntrustOrder")
	proto.RegisterType((*EntrustRevokeOrder)(nil), "types.EntrustRevokeOrder")
	proto.RegisterType((*RevokeOrder)(nil), "types.RevokeOrder")
	proto.RegisterType((*Asset)(nil), "types.asset")
	proto.RegisterType((*Order)(nil), "types.Order")
	proto.RegisterType((*QueryMarketDepth)(nil), "types.QueryMarketDepth")
	proto.RegisterType((*MarketDepth)(nil), "types.MarketDepth")
	proto.RegisterType((*MarketDepthList)(nil), "types.MarketDepthList")
	proto.RegisterType((*QueryHistoryOrderList)(nil), "types.QueryHistoryOrderList")
	proto.RegisterType((*QueryOrder)(nil), "types.QueryOrder")
	proto.RegisterType((*QueryOrderList)(nil), "types.QueryOrderList")
	proto.RegisterType((*OrderList)(nil), "types.OrderList")
	proto.RegisterType((*ReceiptExchange)(nil), "types.ReceiptExchange")
	proto.RegisterType((*ReceiptExchangeBind)(nil), "types.ReceiptExchangeBind")
	proto.RegisterType((*DexAccountBalance)(nil), "types.DexAccountBalance")
	proto.RegisterType((*DexAccount)(nil), "types.DexAccount")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExchangeClient is the client API for Exchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExchangeClient interface {
}

type exchangeClient struct {
	cc *grpc.ClientConn
}

func NewExchangeClient(cc *grpc.ClientConn) ExchangeClient {
	return &exchangeClient{cc}
}

// ExchangeServer is the server API for Exchange service.
type ExchangeServer interface {
}

func RegisterExchangeServer(s *grpc.Server, srv ExchangeServer) {
	s.RegisterService(&_Exchange_serviceDesc, srv)
}

var _Exchange_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.exchange",
	HandlerType: (*ExchangeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "spot.proto",
}

func init() { proto.RegisterFile("spot.proto", fileDescriptor_spot_18062e3d09ef4ab5) }

var fileDescriptor_spot_18062e3d09ef4ab5 = []byte{
	// 1206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x4d, 0x6f, 0x23, 0x45,
	0x13, 0xce, 0x7c, 0x38, 0x8e, 0xcb, 0xb1, 0xb3, 0xe9, 0xec, 0xfb, 0x6a, 0x58, 0x50, 0x14, 0x8d,
	0x50, 0x88, 0xd0, 0x2a, 0x61, 0x1d, 0x09, 0xc4, 0xd1, 0x51, 0xb2, 0x1b, 0xb4, 0xbb, 0x7c, 0xf4,
	0xc2, 0x4a, 0xe4, 0x02, 0x13, 0x4f, 0xc7, 0x6e, 0x79, 0x3c, 0x33, 0x9a, 0xe9, 0xc9, 0xc6, 0x8b,
	0xc4, 0x85, 0x1f, 0x80, 0xb8, 0x70, 0xe1, 0xcc, 0x95, 0x03, 0xbf, 0x80, 0x03, 0x9c, 0xf9, 0x4b,
	0xa8, 0xab, 0x7b, 0x66, 0x7a, 0xec, 0xc0, 0x06, 0x50, 0xc4, 0xc9, 0x53, 0x4f, 0x75, 0x75, 0x3d,
	0x5d, 0x55, 0x5d, 0xd5, 0x06, 0xc8, 0xd3, 0x44, 0xec, 0xa7, 0x59, 0x22, 0x12, 0xd2, 0x12, 0xf3,
	0x94, 0xe5, 0xf7, 0x7a, 0x2f, 0xb8, 0x88, 0x59, 0x9e, 0x2b, 0xd4, 0x07, 0x58, 0x3b, 0xb9, 0x1a,
	0x4d, 0x82, 0x78, 0xcc, 0xfc, 0xef, 0x1c, 0xe8, 0x97, 0xc2, 0x70, 0x24, 0x78, 0x12, 0x93, 0x43,
	0x80, 0x88, 0xcf, 0xb8, 0xf8, 0x28, 0x0b, 0x59, 0xe6, 0x59, 0x3b, 0xd6, 0x5e, 0x77, 0xb0, 0xb9,
	0x8f, 0x3b, 0xed, 0x3f, 0xa9, 0x14, 0xa7, 0x2b, 0xd4, 0x58, 0x46, 0xde, 0x85, 0xee, 0x2c, 0xc8,
	0xa6, 0x4c, 0x5b, 0xd9, 0x68, 0x45, 0xb4, 0xd5, 0xd3, 0x5a, 0x73, 0xba, 0x42, 0xcd, 0x85, 0xd2,
	0x2e, 0x63, 0x97, 0xc9, 0x94, 0x29, 0x3b, 0xa7, 0x61, 0x47, 0x6b, 0x8d, 0xb4, 0x33, 0x16, 0x92,
	0xf7, 0x61, 0x9d, 0x69, 0xda, 0x47, 0x3c, 0x0e, 0x3d, 0x17, 0x0d, 0xb7, 0xb4, 0xe1, 0x89, 0xa1,
	0x3a, 0x5d, 0xa1, 0x8d, 0xa5, 0x68, 0x1a, 0x8b, 0xac, 0xc8, 0x35, 0xd7, 0x56, 0xd3, 0xd4, 0x50,
	0xa1, 0xa9, 0x21, 0x93, 0xc7, 0x40, 0xb4, 0x6c, 0x50, 0xf3, 0xda, 0xb8, 0xc1, 0x6b, 0xcd, 0x0d,
	0x9a, 0xdc, 0xaf, 0x31, 0x23, 0x7d, 0xb0, 0xc5, 0xdc, 0x5b, 0xdd, 0xb1, 0xf6, 0x5a, 0xd4, 0x16,
	0xf3, 0xa3, 0x36, 0xb4, 0x2e, 0x83, 0xa8, 0x60, 0xfe, 0xef, 0x36, 0xb4, 0xcf, 0xa6, 0x6a, 0xd1,
	0x1b, 0xd0, 0x09, 0x46, 0xa3, 0xa4, 0x88, 0xc5, 0x07, 0xc7, 0x98, 0x0b, 0x97, 0xd6, 0x00, 0xd9,
	0x06, 0x60, 0x62, 0x32, 0x0c, 0xc3, 0x8c, 0xe5, 0x39, 0x06, 0xbd, 0x43, 0x0d, 0x84, 0xdc, 0x85,
	0x56, 0x9c, 0xc4, 0x23, 0x86, 0x71, 0x75, 0xa9, 0x12, 0xe4, 0x9e, 0x22, 0x99, 0xb2, 0xf8, 0x19,
	0x8b, 0x22, 0x0c, 0x5c, 0x8f, 0xd6, 0x00, 0xb9, 0x07, 0x6b, 0x28, 0x1c, 0x15, 0x73, 0x0c, 0x4d,
	0x8f, 0x56, 0x32, 0xf9, 0x3f, 0xac, 0x06, 0x33, 0xe9, 0x1b, 0x69, 0xbb, 0x54, 0x4b, 0x12, 0xcf,
	0x02, 0xc1, 0x93, 0x07, 0x18, 0x8b, 0x1e, 0xd5, 0x52, 0x85, 0x0f, 0xbc, 0x35, 0x03, 0x1f, 0x48,
	0x06, 0x97, 0x41, 0xc4, 0xc3, 0x87, 0x59, 0x32, 0xf3, 0x3a, 0xea, 0x54, 0x15, 0x20, 0x4f, 0x85,
	0xc2, 0x67, 0xb1, 0xe0, 0x91, 0x07, 0xa8, 0x36, 0x10, 0xf2, 0x0e, 0x74, 0x72, 0x3e, 0x8e, 0x03,
	0x51, 0x64, 0xcc, 0xbb, 0xdb, 0xa8, 0x98, 0xb3, 0xe9, 0xb3, 0x52, 0x43, 0xeb, 0x45, 0xfe, 0x4f,
	0x16, 0x40, 0x5d, 0xba, 0xd2, 0x7d, 0xc4, 0x2e, 0xc4, 0x30, 0xcf, 0x99, 0xc0, 0xa0, 0xf6, 0x68,
	0x0d, 0x48, 0xf7, 0x19, 0x1f, 0x4f, 0xb4, 0xda, 0x46, 0xb5, 0x81, 0xc8, 0xa0, 0xa6, 0x19, 0xd7,
	0x41, 0x75, 0xa8, 0x12, 0x8c, 0xd0, 0xb8, 0x08, 0x97, 0xa1, 0xe9, 0x83, 0x9d, 0xa4, 0x18, 0xc8,
	0x16, 0xb5, 0x93, 0x94, 0xbc, 0x09, 0xad, 0x04, 0xab, 0x66, 0x15, 0x89, 0xf7, 0x2b, 0xe2, 0x48,
	0x8d, 0x2a, 0xa5, 0xff, 0xad, 0x05, 0x5d, 0xe3, 0xd6, 0x90, 0xb7, 0x17, 0x19, 0x77, 0x07, 0xeb,
	0xda, 0x32, 0x90, 0x98, 0xc9, 0xff, 0xfe, 0x12, 0xff, 0xc5, 0xc5, 0xe6, 0x69, 0x6a, 0xde, 0xce,
	0x35, 0xbc, 0xdd, 0x92, 0xb7, 0xff, 0x25, 0xac, 0x9b, 0xb7, 0x8a, 0xec, 0xc1, 0x46, 0x79, 0xab,
	0xca, 0xfa, 0xb3, 0xb0, 0xfe, 0x16, 0x61, 0xb2, 0x0b, 0x7d, 0x5d, 0xfd, 0xcd, 0x42, 0x5d, 0x40,
	0xfd, 0x5f, 0x2d, 0x58, 0x37, 0x6f, 0xdf, 0x7f, 0x9a, 0x26, 0x02, 0x6e, 0x10, 0x86, 0x2a, 0x4b,
	0x1d, 0x8a, 0xdf, 0x75, 0xea, 0xda, 0x7f, 0x95, 0xba, 0x23, 0x20, 0xcb, 0x2d, 0x80, 0x78, 0xd0,
	0x46, 0xb5, 0xbe, 0xc5, 0x0e, 0x2d, 0xc5, 0xca, 0x93, 0x5d, 0x7b, 0xf2, 0xdf, 0x82, 0xee, 0x8d,
	0x8c, 0xfd, 0xf7, 0xa0, 0x15, 0x94, 0x69, 0x64, 0x57, 0x6c, 0xa4, 0x1b, 0x76, 0x87, 0x6a, 0x49,
	0xe2, 0xf9, 0x7c, 0x76, 0x9e, 0x44, 0x7a, 0x7f, 0x2d, 0xf9, 0xbf, 0xb8, 0xd0, 0x7a, 0x15, 0xb3,
	0xe6, 0x20, 0xb0, 0xff, 0xd1, 0x20, 0x70, 0x6e, 0x3a, 0x08, 0x54, 0x37, 0x74, 0xcb, 0x6e, 0x28,
	0xdb, 0x90, 0x3c, 0x42, 0x21, 0x58, 0x88, 0x69, 0x71, 0x68, 0x25, 0x93, 0xd7, 0xa1, 0x33, 0x7c,
	0xfe, 0xe8, 0x0b, 0x95, 0xde, 0x55, 0xa5, 0x1c, 0x3e, 0x7f, 0xf4, 0x31, 0x66, 0xd8, 0x83, 0xf6,
	0x79, 0x10, 0x05, 0xb2, 0xeb, 0xb5, 0xd5, 0x79, 0xb4, 0x88, 0xb1, 0x10, 0x81, 0x28, 0x72, 0xec,
	0x46, 0x2d, 0xaa, 0xa5, 0x2a, 0x03, 0x1d, 0x23, 0xd7, 0xdb, 0x00, 0x45, 0x1a, 0x06, 0x82, 0x7d,
	0xca, 0x67, 0x0c, 0x7b, 0x90, 0x43, 0x0d, 0x44, 0x56, 0x17, 0x8f, 0x43, 0x76, 0xe5, 0x75, 0x55,
	0x75, 0xa1, 0x20, 0x77, 0xca, 0x02, 0xc1, 0xbc, 0x75, 0xdc, 0x1f, 0xbf, 0xc9, 0x0e, 0x74, 0x43,
	0x3e, 0x66, 0xb9, 0x60, 0xe1, 0x43, 0xc6, 0xbc, 0x1e, 0xae, 0x37, 0x21, 0xc9, 0x6b, 0xc6, 0x63,
	0xa9, 0xec, 0xab, 0x9a, 0x54, 0x92, 0xdc, 0x6d, 0x12, 0xe4, 0x13, 0x6f, 0x43, 0xf1, 0x92, 0xdf,
	0x58, 0xf5, 0x58, 0x19, 0xa7, 0x52, 0x73, 0x47, 0x75, 0xfc, 0x1a, 0x91, 0xfa, 0x51, 0xc6, 0x4a,
	0xde, 0x9b, 0x8a, 0x77, 0x8d, 0x48, 0x36, 0xc6, 0xb5, 0xf3, 0x08, 0x6e, 0x60, 0x42, 0x72, 0x87,
	0x0b, 0xc6, 0x8e, 0x74, 0x08, 0xb7, 0xd4, 0x0e, 0x35, 0x52, 0x8f, 0xa9, 0x9f, 0x2d, 0xb8, 0xf3,
	0x49, 0xc1, 0xb2, 0xb9, 0xca, 0xea, 0x31, 0x4b, 0xc5, 0xe4, 0x16, 0x1b, 0x95, 0xba, 0xa1, 0x4e,
	0x75, 0x43, 0xb7, 0x01, 0xd2, 0x8c, 0xcf, 0x82, 0x6c, 0xfe, 0x98, 0xa9, 0xc2, 0xe9, 0x50, 0x03,
	0x91, 0x19, 0xc2, 0x31, 0xa9, 0x2f, 0xb5, 0x12, 0xfc, 0x1f, 0xab, 0xc6, 0x7a, 0xdb, 0x7c, 0xff,
	0x55, 0xff, 0xf1, 0x3f, 0x87, 0x0d, 0x83, 0xe6, 0x13, 0x9e, 0x0b, 0xb2, 0x0b, 0x6e, 0xc4, 0x73,
	0xc9, 0xd2, 0x59, 0xba, 0x52, 0xb8, 0x8a, 0xa2, 0x7e, 0x21, 0x30, 0xf6, 0x62, 0x60, 0xfc, 0xdf,
	0x2c, 0xf8, 0x1f, 0xe6, 0xed, 0x94, 0xe7, 0x22, 0xc9, 0xe6, 0x78, 0xff, 0xd0, 0xc3, 0xed, 0x05,
	0xa3, 0xc9, 0xc9, 0xf9, 0xf3, 0x64, 0xb9, 0x46, 0xb2, 0xe4, 0x00, 0x08, 0x79, 0xc6, 0xf0, 0x59,
	0xaa, 0x63, 0x53, 0x03, 0xfe, 0x2e, 0x00, 0x1e, 0xe3, 0x55, 0x3d, 0xf2, 0x7b, 0x0b, 0xfa, 0xf5,
	0x42, 0x3c, 0x68, 0xdd, 0x09, 0xac, 0x46, 0x27, 0xf0, 0xa0, 0x1d, 0x34, 0x66, 0x54, 0x29, 0xde,
	0xca, 0x01, 0x9e, 0x42, 0xa7, 0xa6, 0xb4, 0xd3, 0xc8, 0x6e, 0x19, 0x49, 0x35, 0x59, 0x6e, 0x96,
	0xd7, 0xaf, 0x60, 0x83, 0xb2, 0x11, 0xe3, 0xa9, 0x28, 0x07, 0x35, 0xf1, 0xcb, 0x89, 0xd5, 0x4c,
	0xa6, 0x39, 0xaf, 0xc8, 0xbe, 0x6c, 0xd8, 0x62, 0x34, 0x41, 0x50, 0x9e, 0x7b, 0xd9, 0xbf, 0xb9,
	0xa0, 0xee, 0x7c, 0x8e, 0xd1, 0xf9, 0xfc, 0x1f, 0x2c, 0xd8, 0x5a, 0xf0, 0xfe, 0x37, 0x9f, 0x09,
	0xf7, 0x61, 0x33, 0x66, 0x2f, 0x4e, 0xae, 0x7b, 0x29, 0x2c, 0x2b, 0xe4, 0xea, 0x24, 0x0a, 0x17,
	0x56, 0xab, 0xb4, 0x2c, 0x2b, 0xfc, 0x6f, 0x2c, 0xd8, 0x3c, 0x66, 0x57, 0x43, 0xf5, 0x70, 0xd6,
	0x9d, 0x4c, 0xde, 0x39, 0x1e, 0xea, 0x87, 0x85, 0xcd, 0x43, 0x73, 0x72, 0xd8, 0xf8, 0xe8, 0x34,
	0x27, 0xc7, 0x45, 0x96, 0xbc, 0x64, 0xb1, 0x7e, 0x48, 0x6b, 0xa9, 0x9a, 0x1c, 0xae, 0x31, 0x39,
	0x3c, 0x68, 0x87, 0xec, 0xea, 0xc3, 0x60, 0xc6, 0x30, 0xe3, 0x1d, 0x5a, 0x8a, 0xfe, 0xd7, 0x00,
	0x35, 0x09, 0xc3, 0xbb, 0x8b, 0xde, 0xaf, 0x79, 0x07, 0x90, 0x41, 0xcd, 0xc8, 0xc1, 0xbc, 0x78,
	0x3a, 0x2f, 0x4b, 0x87, 0xa9, 0xb9, 0x1a, 0xfe, 0xdd, 0x86, 0xff, 0x01, 0xc8, 0x91, 0xaa, 0x73,
	0xf3, 0xe0, 0xec, 0x60, 0xcc, 0xc5, 0xa4, 0x38, 0xdf, 0x1f, 0x25, 0xb3, 0x83, 0xc3, 0xc3, 0x51,
	0x7c, 0x90, 0x46, 0xc5, 0x98, 0x57, 0x3f, 0x61, 0x90, 0xa6, 0x07, 0x2f, 0xa7, 0xf2, 0xcf, 0xe4,
	0x01, 0xfa, 0x3c, 0x5f, 0xc5, 0x7f, 0x8f, 0x87, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x61, 0xce,
	0x56, 0x00, 0x61, 0x0e, 0x00, 0x00,
}
